# Generated by Django 4.2.30 on 2026-06-10 19:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceDocumentsList',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_info', models.TextField(blank=True, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField()),
                ('is_required_default', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('validity_years', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Compliance Document',
                'verbose_name_plural': 'Compliance Documents List',
                'db_table': 'compliance_documents_list',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SellerOptionalUploads',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('custom_title', models.CharField(blank=True, max_length=255, null=True)),
                ('custom_description', models.TextField(blank=True, null=True)),
                ('file_url', models.URLField(max_length=2048)),
                ('status', models.CharField(max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('expired', models.BooleanField()),
                ('document_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='compliance.compliancedocumentslist')),
                ('reviewed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.adminusers')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.users')),
            ],
            options={
                'db_table': 'seller_optional_uploads',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SellerComplianceDocuments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_required', models.BooleanField()),
                ('status', models.CharField(max_length=30)),
                ('file_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.IntegerField()),
                ('is_current', models.BooleanField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('expired', models.BooleanField()),
                ('document_list', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compliance.compliancedocumentslist')),
                ('reviewed_by_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.adminusers')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.users')),
            ],
            options={
                'verbose_name': 'Seller Compliance Document',
                'verbose_name_plural': 'Seller Compliance Documents',
                'db_table': 'seller_compliance_documents',
                'managed': True,
                'unique_together': {('seller', 'document_list')},
            },
        ),
    ]
