import { StyleSheet } from 'react-native';

export const foodCardStyles = StyleSheet.create({
  foodCardWrap: {
    marginBottom: 16,
    marginHorizontal: 6,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOpacity: 0.14,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 5 },
    elevation: 5,
  },
  foodCardWrapTablet: {
    marginHorizontal: 0,
    marginBottom: 14,
  },
  foodCard: {
    borderWidth: 1,
    borderRadius: 12,
    overflow: 'hidden',
    position: 'relative',
  },
  foodPhoto: {
    width: '100%',
    height: 180,
    overflow: 'hidden',
    backgroundColor: '#B96C44',
  },
  foodPhotoTablet: {
    height: 150,
  },
  foodImageCarousel: {
    width: '100%',
    height: '100%',
  },
  foodImageCarouselContent: {
    height: '100%',
  },
  foodImageSlide: {
    height: '100%',
    overflow: 'hidden',
  },
  foodImage: {
    ...StyleSheet.absoluteFillObject,
  },
  foodImageFallback: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#8E593C',
  },
  foodPhotoDotsRow: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 8,
    zIndex: 7,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
  },
  foodPhotoDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: 'rgba(255,255,255,0.38)',
  },
  foodPhotoDotActive: {
    width: 16,
    borderRadius: 4,
    backgroundColor: '#F5D08A',
  },
  foodBadgesRight: {
    position: 'absolute',
    top: 14,
    right: 14,
    alignItems: 'flex-end',
    gap: 8,
    zIndex: 7,
  },
  foodBadgesRightTablet: {
    top: 10,
    right: 10,
    gap: 6,
  },
  foodRatingBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: 'rgba(51,36,27,0.9)',
    borderRadius: 18,
    paddingHorizontal: 11,
    paddingVertical: 7,
  },
  foodRatingBadgeTablet: {
    gap: 4,
    borderRadius: 14,
    paddingHorizontal: 8,
    paddingVertical: 5,
  },
  foodRatingBadgeText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontWeight: '900',
  },
  foodRatingBadgeTextTablet: {
    fontSize: 11,
  },
  foodPhotoTitleOverlay: {
    position: 'absolute',
    left: 18,
    right: 16,
    bottom: 14,
    zIndex: 7,
  },
  foodPhotoTitleText: {
    color: '#FFFFFF',
    fontSize: 39,
    fontWeight: '900',
    fontStyle: 'italic',
    letterSpacing: -2,
    textShadowColor: 'rgba(0,0,0,1)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 6,
  },
  foodPhotoTitleTextTablet: {
    fontSize: 27,
    letterSpacing: -1,
    lineHeight: 31,
  },
  foodPhotoCuisineText: {
    marginTop: 1,
    color: '#FFFFFF',
    fontSize: 15,
    fontWeight: '700',
    textShadowColor: 'rgba(0,0,0,1)',
    textShadowOffset: { width: 0, height: 0 },
    textShadowRadius: 4,
  },
  foodPhotoCuisineTextTablet: {
    fontSize: 12,
    lineHeight: 15,
  },
  foodPriceBadge: {
    backgroundColor: 'rgba(51,36,27,0.9)',
    borderRadius: 18,
    paddingHorizontal: 13,
    paddingVertical: 8,
  },
  foodPriceBadgeTablet: {
    borderRadius: 14,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  foodPriceBadgeText: { color: '#FFFFFF', fontSize: 17, fontWeight: '900' },
  foodPriceBadgeTextTablet: { fontSize: 13 },
  foodPriceBadgeClean: {
    backgroundColor: 'rgba(255,255,255,0.95)',
    shadowColor: '#000',
    shadowOpacity: 0.10,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  foodPriceBadgeTextClean: {
    color: '#2F221B',
    fontSize: 15,
    fontWeight: '800',
  },
  foodTitleRow: {
    flexDirection: 'row',
    alignItems: 'baseline',
    justifyContent: 'space-between',
    gap: 10,
    paddingTop: 4,
    paddingBottom: 6,
  },
  foodTitleClean: {
    flex: 1,
    minWidth: 0,
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: -0.2,
  },
  foodCuisineClean: {
    fontSize: 12,
    fontWeight: '500',
    flexShrink: 0,
  },
  foodFooterHandleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
  },
  foodFooterSellerLink: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 2,
  },
  foodFooterRatingInline: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 3,
    flexShrink: 0,
  },
  foodFooterRatingInlineText: {
    fontSize: 12,
    fontWeight: '700',
  },
  foodPhotoFavoriteBtn: {
    position: 'absolute',
    right: 12,
    bottom: 12,
    width: 32,
    height: 32,
    borderRadius: 16,
    borderWidth: 1.2,
    borderColor: 'rgba(255,255,255,0.48)',
    backgroundColor: 'rgba(76,56,42,0.18)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 7,
    shadowColor: '#1F130D',
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 6 },
    elevation: 6,
  },
  foodPhotoFavoriteBtnTablet: {
    right: 10,
    bottom: 10,
    width: 36,
    height: 36,
    borderRadius: 18,
  },
  foodInfo: {
    backgroundColor: '#FFFDF9',
    borderTopWidth: 1,
    borderTopColor: 'rgba(92,72,56,0.08)',
    overflow: 'visible',
  },
  foodInfoContent: {
    paddingTop: 8,
    paddingBottom: 6,
    paddingHorizontal: 13,
    overflow: 'visible',
  },
  foodInfoContentTablet: {
    paddingTop: 6,
    paddingBottom: 6,
    paddingHorizontal: 10,
  },
  foodInfoChipRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 5,
    paddingBottom: 8,
  },
  foodInfoDivider: {
    width: 1,
    height: 18,
    borderRadius: 1,
    flexShrink: 0,
  },
  foodInfoChip: {
    minHeight: 24,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 3,
    flexShrink: 1,
    minWidth: 0,
  },
  foodInfoChipText: {
    fontSize: 11.5,
    lineHeight: 14,
    fontWeight: '800',
    letterSpacing: -0.15,
    flexShrink: 1,
  },
  foodInfoChipTextTablet: {
    fontSize: 10.5,
    lineHeight: 13,
    letterSpacing: 0,
  },
  foodInfoMainRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 14,
    marginBottom: 0,
  },
  foodInfoHalfCol: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    minWidth: 0,
  },
  foodInfoRightHalfCol: {
    justifyContent: 'flex-end',
    paddingLeft: 10,
  },
  foodInfoIconBubble: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#F1EAE2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  foodInfoIconBubbleAlert: {
    backgroundColor: '#FBE8E4',
  },
  foodInfoIconBubbleOk: {
    backgroundColor: '#E4F2EB',
  },
  foodInfoTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  foodInfoTextWrapCentered: {
    minHeight: 26,
    justifyContent: 'center',
  },
  foodInfoTitle: {
    color: '#2F241D',
    fontSize: 12,
    fontWeight: '800',
    lineHeight: 15,
  },
  foodInfoSubtitle: {
    marginTop: 0,
    color: '#6F6256',
    fontSize: 11,
    fontWeight: '600',
    lineHeight: 13,
  },
  foodStatsRow: {
    marginTop: 4,
    paddingBottom: 4,
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: 0,
  },
  foodStatDivider: {
    width: 1,
    backgroundColor: 'rgba(92,72,56,0.10)',
    marginLeft: 2,
    marginRight: 8,
    alignSelf: 'stretch',
    flexShrink: 0,
  },
  foodFooterRow: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(92,72,56,0.08)',
    marginTop: 0,
    paddingTop: 7,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    overflow: 'visible',
  },
  foodFooterSeller: {
    flex: 1,
    minWidth: 0,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 7,
    overflow: 'visible',
  },
  foodSellerThumbWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    position: 'relative',
    zIndex: 12,
    transform: [{ translateY: 0 }],
    shadowColor: '#000',
    shadowOpacity: 0.12,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  foodSellerThumb: {
    width: '100%',
    height: '100%',
    borderRadius: 14,
    overflow: 'hidden',
    borderWidth: 0.7,
    borderColor: 'rgba(141,128,114,0.24)',
    backgroundColor: '#F4EEE6',
  },
  foodSellerThumbImage: { width: '100%', height: '100%' },
  foodSellerThumbFallback: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  foodSellerThumbFallbackText: { color: '#6D5D50', fontSize: 18, fontWeight: '800' },
  foodFooterSellerText: {
    flex: 1,
    minWidth: 0,
    justifyContent: 'center',
    paddingTop: 0,
  },
  foodFooterSellerHandle: {
    color: '#33241C',
    fontSize: 12,
    fontWeight: '900',
    lineHeight: 15,
  },
  foodFooterSellerHandleTablet: {
    fontSize: 11,
    lineHeight: 14,
  },
  foodFooterSellerTagline: {
    marginTop: 4,
    color: '#7D695A',
    fontSize: 10.5,
    fontWeight: '500',
    fontStyle: 'italic',
    lineHeight: 13,
    opacity: 0.82,
  },
  foodFooterSellerTaglineTablet: {
    marginTop: 3,
    fontSize: 9.5,
    lineHeight: 12,
  },
  foodFooterFavoriteBtnActive: {
    backgroundColor: 'rgba(161,58,47,0.52)',
    borderColor: 'rgba(255,240,236,0.72)',
  },
});
