# Generated by Django 4.2.30 on 2026-06-10 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('orders', '0001_initial'),
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orders'),
        ),
        migrations.AddField(
            model_name='complaintadminnotes',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='complaints.complaints'),
        ),
        migrations.AddField(
            model_name='complaintadminnotes',
            name='created_by_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.adminusers'),
        ),
    ]
