# Generated by Django 4.2.30 on 2026-06-10 19:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=30)),
                ('delivery_type', models.CharField(max_length=30)),
                ('delivery_address_json', models.JSONField(blank=True, null=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('payment_completed', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_delivery_type', models.CharField(max_length=30)),
                ('active_delivery_type', models.CharField(max_length=30)),
                ('seller_decision_state', models.CharField(max_length=30)),
                ('seller_eta_minutes', models.IntegerField(blank=True, null=True)),
                ('seller_promised_at', models.DateTimeField(blank=True, null=True)),
                ('seller_delivery_note', models.TextField(blank=True, null=True)),
                ('seller_delivery_terms_snapshot', models.TextField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('payment_captured_at', models.DateTimeField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.users')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders_seller_set', to='authentication.users')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OutboxEvents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('aggregate_type', models.CharField(max_length=50)),
                ('aggregate_id', models.CharField(max_length=255)),
                ('payload_json', models.JSONField()),
                ('status', models.CharField(max_length=30)),
                ('attempt_count', models.IntegerField()),
                ('next_attempt_at', models.DateTimeField()),
                ('last_error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outbox_events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OutboxDeadLetters',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('aggregate_type', models.CharField(max_length=50)),
                ('aggregate_id', models.CharField(max_length=255)),
                ('payload_json', models.JSONField()),
                ('last_error', models.TextField(blank=True, null=True)),
                ('failed_at', models.DateTimeField()),
                ('outbox_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='orders.outboxevents')),
            ],
            options={
                'db_table': 'outbox_dead_letters',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('food_id', models.UUIDField()),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('selected_addons_json', models.JSONField(blank=True, null=True)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='menu.productionlots')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orders')),
            ],
            options={
                'db_table': 'order_items',
                'managed': True,
                'unique_together': {('order', 'lot')},
            },
        ),
        migrations.CreateModel(
            name='OrderItemLotAllocations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_allocated', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.productionlots')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orders')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orderitems')),
            ],
            options={
                'db_table': 'order_item_lot_allocations',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderFinance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('commission_rate_snapshot', models.DecimalField(decimal_places=4, max_digits=5)),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('seller_net_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('finalized_at', models.DateTimeField()),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orders')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.users')),
            ],
            options={
                'db_table': 'order_finance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderEvents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('from_status', models.CharField(blank=True, max_length=30, null=True)),
                ('to_status', models.CharField(blank=True, max_length=30, null=True)),
                ('payload_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.users')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orders')),
            ],
            options={
                'db_table': 'order_events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrderDeliveryTracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('accuracy_m', models.IntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orders')),
                ('seller_user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.users')),
            ],
            options={
                'db_table': 'order_delivery_tracking',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DeliveryProofRecords',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('proof_mode', models.CharField(max_length=30)),
                ('pin_hash', models.CharField(max_length=255)),
                ('pin_sent_at', models.DateTimeField(blank=True, null=True)),
                ('pin_sent_channel', models.CharField(max_length=20)),
                ('pin_verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_attempts', models.IntegerField()),
                ('status', models.CharField(max_length=30)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='deliveryproofrecords_buyer_set', to='authentication.users')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orders')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.users')),
            ],
            options={
                'db_table': 'delivery_proof_records',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('images_json', models.JSONField(blank=True, null=True)),
                ('helpful_count', models.IntegerField()),
                ('report_count', models.IntegerField()),
                ('is_verified_purchase', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.users')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.foods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orders')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reviews_seller_set', to='authentication.users')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'db_table': 'reviews',
                'managed': True,
                'unique_together': {('buyer', 'food', 'order')},
            },
        ),
        migrations.CreateModel(
            name='OrderNotificationMilestones',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestone_type', models.CharField(max_length=50)),
                ('sent_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orders')),
            ],
            options={
                'db_table': 'order_notification_milestones',
                'managed': True,
                'unique_together': {('order', 'milestone_type')},
            },
        ),
        migrations.CreateModel(
            name='AllergenDisclosureRecords',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phase', models.CharField(max_length=30)),
                ('allergen_snapshot_json', models.JSONField()),
                ('disclosure_method', models.CharField(max_length=50)),
                ('buyer_confirmation', models.CharField(max_length=30)),
                ('evidence_ref', models.CharField(blank=True, max_length=255, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='allergendisclosurerecords_buyer_set', to='authentication.users')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.foods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orders')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.users')),
            ],
            options={
                'db_table': 'allergen_disclosure_records',
                'managed': True,
                'unique_together': {('order', 'phase')},
            },
        ),
    ]
