# Generated by Django 4.2.30 on 2026-06-10 19:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_message', models.TextField(blank=True, null=True)),
                ('last_message_time', models.DateTimeField(blank=True, null=True)),
                ('last_message_sender', models.CharField(blank=True, max_length=50, null=True)),
                ('buyer_unread_count', models.IntegerField()),
                ('seller_unread_count', models.IntegerField()),
                ('is_active', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer_chats', to='authentication.users')),
            ],
            options={
                'db_table': 'chats',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserDeviceTokens',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.TextField(unique=True)),
                ('platform', models.CharField(max_length=20)),
                ('app_version', models.CharField(blank=True, max_length=30, null=True)),
                ('is_active', models.BooleanField()),
                ('last_seen_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.users')),
            ],
            options={
                'db_table': 'user_device_tokens',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='NotificationEvents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('data_json', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.users')),
            ],
            options={
                'db_table': 'notification_events',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(max_length=20)),
                ('message', models.TextField(blank=True, null=True)),
                ('message_type', models.CharField(max_length=20)),
                ('order_data_json', models.JSONField(blank=True, null=True)),
                ('is_read', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='messages', to='notifications.chats')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_chat_messages', to='authentication.users')),
            ],
            options={
                'db_table': 'messages',
                'managed': True,
            },
        ),
    ]
