import { getCurrentLanguage } from '../utils/settings';

export const brandCopy = {
  'headline.home.greetingTitle': 'Günaydın, Lale',
  'headline.home.greetingSubtitle': 'Bugün ne yesek?',
  'headline.home.slogan': 'Komşunun mutfağından, kapına.',
  'helper.home.sloganSubline': 'Yakınındaki ev şeflerinden sıcacık yemekler',
  'helper.home.searchPlaceholder': 'Yemek ya da usta ara...',
  'helper.home.stockLimitTitle': 'Stok sınırı',
  'helper.home.stockLimitMessage': 'Bu yemekten kalan kadar listene ekleyebilirsin.',
  'helper.home.stockLinePrefix': 'kaldı',
  'status.home.stockLineSuffix': 'porsiyon',
  'helper.home.cartEmptyTitle': 'Yemek listen şu an boş.',
  'headline.home.pendingListTitle': 'Listen şefe iletildi',
  'helper.home.pendingListSubtitle': 'Şu an beklemede. Şef planı onaylayınca sana bildirim gelecektir.',
  'cta.home.cartCheckout': 'Şefe sor',
  'helper.home.cartCheckoutHint': 'Bu buton yemek listeni şefe gönderir. Şef planı netleştirince sana haber veririz.',
  'cta.home.paymentRefresh': 'Durumu yenile',
  'cta.home.backHome': 'Ana sayfaya dön',
  'cta.home.paymentNext': 'Sonraki ödeme',
  'status.home.paymentTitle': 'Sofra durumu',
  'status.home.orderLabel': 'Liste:',
  'status.home.orderStatusLabel': 'Durum:',
  'status.home.paymentDone': 'Ödeme tamamlandı',
  'status.home.paymentWaiting': 'Satıcı onayı bekleniyor',
  'status.home.orderStatus.pending_seller_approval': 'Satıcı onayı bekleniyor',
  'status.home.orderStatus.seller_approved': 'Usta onayladı',
  'status.home.orderStatus.awaiting_payment': 'Ödeme alınıyor',
  'status.home.orderStatus.preparing': 'Hazırlanıyor',
  'status.home.orderStatus.ready': 'Hazır',
  'status.home.orderStatus.in_delivery': 'Yolda',
  'status.home.orderStatus.at_door': 'Kapıda',
  'status.home.orderStatus.delivered': 'Teslim Edildi',
  'status.home.orderStatus.completed': 'Teslim Edildi',
  'status.home.orderStatus.cancelled': 'İptal edildi',
  'status.home.orderStatus.rejected': 'İptal edildi',
  'status.home.paymentAttempt.initiated': 'Ödeme başlatıldı',
  'status.home.paymentAttempt.pending': 'Ödeme beklemede',
  'status.home.paymentAttempt.processing': 'Ödeme işleniyor',
  'status.home.paymentAttempt.succeeded': 'Ödeme başarılı',
  'status.home.paymentAttempt.failed': 'Ödeme başarısız',
  'status.home.paymentAttempt.canceled': 'Ödeme iptal edildi',
  'status.home.paymentAttempt.requires_action': 'Ödeme işlemi gerekiyor',
  'status.home.notificationsTitle': 'Bildirimler',
  'helper.home.notificationsEmpty': 'Yeni bildirimlerini burada göreceksin.',
  'status.home.messagesTitle': 'Mesajlar',
  'helper.home.messagesSubtitle': 'Ustalarla hızlıca yazış',
  'helper.home.messageInputPlaceholder': 'Mesajını yaz...',
  'status.home.profileTitle': 'Profil',
  'cta.home.profileEdit': 'Profili düzenle',
  'cta.home.myOrders': 'Siparişlerim',
  'helper.home.myOrdersHint': 'Geçmiş ve aktif siparişlerini gör',
  'headline.orders.activeTitle': 'En yeni siparişin',
  'helper.orders.activeSubtitle': 'Henüz tamamlanmadı. Detaya girip son durumu görebilirsin.',
  'headline.orders.completedTitle': 'Tamamlanan siparişlerin',
  'helper.orders.completedSubtitle': 'Daha önce aldığın lezzetler burada.',
  'headline.orders.preparingTitle': 'Bekleyen / Hazırlananlar',
  'headline.orders.routeTitle': 'Yolda / Kapıda',
  'headline.orders.historyTitle': 'Geçmiş siparişlerin',
  'headline.orders.title': 'Siparişlerim',
  'headline.orders.emptyTitle': 'Henüz siparişin yok',
  'helper.orders.emptySubtitle': 'Sipariş verdiğinde burada görünecek.',
  'headline.orders.quickActiveTitle': 'Son siparişin',
  'helper.orders.quickPendingSubtitle': 'Siparişin ustada. Durumu buradan hızlıca görebilirsin.',
  'helper.orders.quickPreparingSubtitle': 'Siparişin ilerliyor. Son durumu buradan takip edebilirsin.',
  'helper.orders.searchPlaceholder': 'Usta, yemek ya da sipariş no ara...',
  'helper.orders.searchEmptyTitle': 'Aradığın siparişi bulamadım',
  'helper.orders.searchEmptySubtitle': 'Kelimeyi biraz değiştirip tekrar dene.',
  'helper.orders.completedEmptyTitle': 'Tamamlanan siparişin yok',
  'helper.orders.completedEmptySubtitle': 'Teslim edilen siparişlerin burada birikecek.',
  'helper.orders.loading': 'Siparişler yükleniyor...',
  'error.orders.load': 'Siparişler yüklenemedi',
  'helper.orders.groupEmpty': 'Bu grupta sipariş yok.',
  'status.orders.sellerFallback': 'Usta',
  'helper.orders.itemsFallback': 'Sipariş kalemleri',
  'status.orders.countSuffix': 'sipariş',
  'cta.orders.openDetail': 'Detayı aç',
  'status.orders.deliveryType.delivery': 'Teslimat',
  'status.orders.deliveryType.pickup': 'Gel al',
  'status.orders.activePill': 'Aktif',
  'status.orders.completedPill': 'Geçmiş',
  'status.orders.newBadge': 'Yeni',
  'cta.orders.viewAll': 'Tüm siparişlerimi göster',
  'cta.home.addresses': 'Adreslerim',
  'cta.home.deliveryAddressChange': 'Teslimat adresi değiştir',
  'helper.home.deliveryAddressHint': 'Siparişlerin bu adrese gider. Farklı yere geçtiysen buradan güncelle.',
  'cta.home.settings': 'Ayarlar',
  'cta.home.security': 'Güvenlik',
  'cta.home.logout': 'Çıkış yap',
  'headline.home.profileSellerTitle': 'Evinde yemek yapıp satmak ister misin?',
  'helper.home.profileSellerBody': "Coziyoo'da mutfağını gelire dönüştür.",
  'cta.home.becomeSeller': 'Satıcı Ol',
  'headline.home.generalSettingsTitle': 'Genel ayarlar',
  'helper.home.generalSettingsBody': 'Uygulama dilini buradan değiştirebilirsin.',
  'helper.home.generalSettingsLanguageLabel': 'Dil seçimi',
  'helper.home.generalSettingsLanguageHint': 'Şimdilik Türkçe ve İngilizce destekleniyor.',
  'cta.home.languageTurkish': 'Türkçe',
  'cta.home.languageEnglish': 'English',
  'status.home.paymentWebTitle': 'Ödeme ekranı',
  'cta.home.close': 'Kapat',
  'error.home.paymentModuleMissing': 'Uygulama içi ödeme modülü bulunamadı.',
  'cta.home.openInBrowser': 'Tarayıcıda aç',
  'error.home.checkoutMissing': 'Ödeme bağlantısı şu an bulunamıyor.',
  'cta.home.addToCart': 'Listeye ekle',
  'status.home.sellerKitchen': 'Usta Mutfağı',
  'status.home.sellerReviews': 'Yorumlar',
  'status.home.sellerReviewsLoading': 'Yorumlar yükleniyor...',
  'helper.home.sellerReviewsEmpty': 'Bu usta için henüz yorum yok.',
  'helper.home.sellerCommentFallback': 'Yorum bırakılmamış.',
  'status.home.sellerMeals': 'Ustanın yemekleri',
  'status.home.agentTitle': 'Mutfak asistanı',
  'cta.home.retry': 'Tekrar dene',
  'status.home.connecting': 'Bağlanıyor...',
  'helper.home.agentInputPlaceholder': 'Mesajını yaz...',
  'error.home.serverUnavailable502': 'Mutfak tarafında kısa bir yoğunluk var (502). Birazdan tekrar dene.',
  'error.home.serverUnavailable503': 'Sunucu şu an meşgul (503). Birazdan tekrar dene.',
  'error.home.serverTimeout504': 'Sunucu geç cevap veriyor (504). Birazdan tekrar dene.',
  'error.home.serverGeneric': 'Sunucuda bir sorun var.',
  'error.home.requestFailed': 'Bir sorun oldu.',
  'error.home.unexpectedResponse': 'Sunucudan beklenmeyen bir cevap geldi.',
  'error.home.noMealsInResponse': 'Şu an yemek listesi alınmıyor.',
  'error.home.retryLater': 'Şu an ulaşılamıyor. Lütfen tekrar dene.',
  'error.home.sessionExpired': 'Oturumun bitmiş. Tekrar giriş yap.',
  'helper.home.cartEmptyAlertTitle': 'Yemek listen boş',
  'helper.home.cartEmptyAlertMessage': 'Önce listene bir yemek ekleyelim.',
  'error.home.payableLotsMissing': 'Yemek listende gönderilecek ürün kalmadı.',
  'helper.home.checkoutDeliveryType': 'Teslimat tipi',
  'cta.home.delivery': 'Teslimat',
  'cta.home.pickup': 'Gel Al',
  'helper.home.checkoutAddress': 'Teslimat adresi',
  'cta.home.changeAddress': 'Adresi değiştir',
  'cta.home.manageAddresses': 'Adreslerimi yönet',
  'helper.home.noDefaultAddress': 'Varsayılan adresin yok. Devam etmek için adres seç.',
  'helper.home.addressRequiredCheckout': 'Teslimat için önce adres seçmelisin.',
  'helper.home.locationDisabledUsingAddress': 'Konumun kapalı, adresine göre hesaplıyorum.',
  'helper.home.addressRequiredTopSold': 'Yakın usta için önce bir adres seçmelisin.',
  'helper.home.addressGeocodeFailed': 'Adresinden konum belirleyemedim. Adresi kontrol edip tekrar dene.',
  'helper.home.noNearbyTopSold': 'Üzgünüm, bu yemek senin yakınında değil.',
  'status.home.locationBasisLive': 'Canlı konum',
  'status.home.locationBasisAddressPrefix': 'Adres:',
  'headline.home.selectAddress': 'Teslimat adresi seç',
  'helper.home.selectAddressSubtitle': 'Bu sipariş için kayıtlı bir adres seç.',
  'helper.home.addressListEmpty': 'Kayıtlı adres bulunamadı.',
  'headline.home.foodListTitle': 'Yemek Listesi',
  'status.home.foodListCountSuffix': 'yemek',
  'helper.home.flowTitle': 'Sofra planı',
  'helper.home.flowStartTypeLabel': 'Başlangıç planı',
  'helper.home.pickupAddressLabel': 'Alım adresi',
  'helper.home.flowNoteLabel': 'Kısa not',
  'helper.home.flowDefaultPickupNote': 'Yemek listen önce satıcıya gider. Satıcı isterse sonradan teslimat teklif edebilir.',
  'cta.home.requestDelivery': 'Delivery isteği oluştur',
  'helper.home.deliveryRequestPending': 'Teslimat isteğin ustaya iletildi.',
  'helper.home.deliveryRequestSuccess': 'Teslimat isteğin ustaya iletildi.',
  'error.home.deliveryRequestFailed': 'Teslimat isteği iletilemedi.',
  'helper.home.pickupAddressLoading': 'Satıcı adresi yükleniyor...',
  'helper.home.pickupAddressMissing': 'Satıcı adresi bulunamadı.',
  'error.home.pickupAddressFailed': 'Satıcı adresi alınamadı.',
  'helper.home.paymentCapturePendingSingle': 'Listen şefe gönderildi. Şu an beklemede. Şef onay verince sana bildirim gelecektir.',
  'helper.home.paymentCapturePendingMultiple': 'Listen şeflere gönderildi. Şu an beklemede. Şefler onay verdikçe sana bildirim gelecektir.',
  'helper.home.paymentCaptureDoneSingle': 'Ödeme tamamlandı! Listen satıcıya iletildi.',
  'helper.home.paymentProgress': '{completed}/{total} ödeme tamamlandı.',
  'helper.home.flowSellerMissing': 'Satıcı bilgisi eksik.',
  'error.home.checkoutCreateFailed': 'Liste gönderilemedi.',
  'error.home.checkoutMissingOrderId': 'Liste kimliği dönmedi.',
  'error.home.checkoutStartFailed': 'Sofra akışı başlatılamadı.',
  'helper.seller.orderDetail.deliveryRequestTitle': 'Alıcı teslimat istedi',
  'helper.seller.orderDetail.deliveryRequestBody': 'Bu sipariş gel al başladı ama alıcı teslimat talebi bıraktı. Yapabiliyorsan teslimatı seçip onayla, yapamıyorsan gel al olarak bırak.',
  'cta.seller.orderDetail.canDeliver': 'Teslimat yapabilirim',
  'cta.seller.orderDetail.keepPickup': 'Gel al kalsın',
  'cta.seller.orderDetail.approveDelivery': 'Teslimatı onayla ve ödemeyi al',
  'cta.seller.orderDetail.approvePickup': 'Gel al olarak onayla',
  'error.home.paymentStatusFailed': 'Ödeme durumu alınamadı.',
  'helper.home.toastAddedToList': 'Yemek listene eklendi',
  'helper.home.allergenTitle': 'Alerjen uyarısı',
  'helper.home.allergenConfirm': 'Bu yemek şu alerjenleri içeriyor:\n\n🔴 {allergens}\n\nYine de listene eklemek istiyor musun?',
  'cta.home.addAnyway': 'Yine de ekle',
  'headline.home.processingTitle': 'Sofra hazırlanıyor',
  'helper.home.processingCreateList': 'Liste hazırlanıyor...',
  'helper.home.processingCapturePayment': 'Ödeme alınıyor...',
  'helper.home.processingSendSeller': 'Satıcıya iletiliyor...',
  'helper.home.processingDone': 'Tamamlandı!',
  'headline.home.processingSuccess': 'Sofran hazır!',
  'headline.home.tabHome': 'Ana Sayfa',
  'headline.home.tabMessages': 'Mesajlar',
  'headline.home.tabOrders': 'Orders',
  'headline.home.tabNotifications': 'Bildirim',

  'headline.login.title': 'Coziyoo',
  'headline.login.subtitle': 'Komşunun mutfağından sıcacık yemeklere hoş geldin',
  'helper.login.emailLabel': 'E-posta',
  'helper.login.emailPlaceholder': 'ornek@mail.com',
  'helper.login.passwordLabel': 'Şifre',
  'helper.login.passwordPlaceholder': '••••••••',
  'cta.login.signIn': 'Giriş yap',
  'cta.login.quickBuyerSignIn': 'Alıcı giriş',
  'cta.login.quickSellerSignIn': 'Satıcı giriş',
  'cta.login.tryAgain': 'Tekrar dene',
  'error.login.invalidCredentials': 'E-posta ya da şifre doğru değil.',
  'error.login.accountLocked': 'Hesabın kilitli. E-postandaki linkle tekrar açabilirsin.',
  'error.login.tooManyAttempts': 'Çok hızlı deneme yaptın. Biraz bekleyip tekrar dene.',
  'error.login.generic': 'Giriş şu an tamamlanamadı.',
  'error.login.emailRequired': 'E-posta yazman gerekiyor.',
  'error.login.passwordRequired': 'Şifre yazman gerekiyor.',
  'error.login.unexpectedResponse': 'Beklenmeyen bir cevap geldi.',
  'error.login.network': 'Bağlantı sorunu var. İnternetini kontrol edip tekrar dene.',

  'headline.address.title': 'Adreslerim',
  'cta.address.retry': 'Tekrar dene',
  'headline.address.emptyTitle': 'Henüz adres eklemedin',
  'helper.address.emptySubtitle': 'Sipariş için önce bir teslimat adresi ekleyelim.',
  'cta.address.add': 'Adres ekle',
  'status.address.default': 'Varsayılan',
  'cta.address.setDefault': 'Varsayılan yap',
  'headline.address.edit': 'Adresi düzenle',
  'headline.address.new': 'Yeni adres',
  'helper.address.titleLabel': 'Adres başlığı',
  'helper.address.titlePlaceholder': 'Ev, iş, aile...',
  'helper.address.addressLabel': 'Açık adres',
  'helper.address.addressPlaceholder': 'Mahalle, sokak, bina, daire...',
  'helper.address.defaultToggle': 'Bunu varsayılan adres yap',
  'cta.address.update': 'Kaydet',
  'cta.address.save': 'Kaydet',
  'error.address.load': 'Adreslerini şu an yükleyemedik.',
  'error.address.titleRequired': 'Adres başlığı boş olamaz.',
  'error.address.addressTooShort': 'Adres en az 3 karakter olmalı.',
  'error.address.save': 'Adresi şu an kaydedemedik.',
  'error.address.delete': 'Adres şu an silinemedi.',
  'error.address.default': 'Varsayılan adres şu an değiştirilemedi.',
  'helper.address.deleteTitle': 'Adresi sil',
  'helper.address.deleteMessage': 'Bu adresi silmek istediğine emin misin?',
  'cta.address.cancel': 'Vazgeç',
  'cta.address.delete': 'Sil',

  'headline.profileEdit.title': 'Profili düzenle',
  'helper.profileEdit.displayNameLabel': 'Görünen isim',
  'helper.profileEdit.displayNamePlaceholder': 'Adın nasıl görünsün?',
  'helper.profileEdit.displayNameHint': 'Uygulamada görünen adın',
  'helper.profileEdit.usernameLabel': 'Kullanıcı adı',
  'helper.profileEdit.usernamePlaceholder': 'lezzetduragi',
  'helper.profileEdit.usernameHint': 'Benzersiz @kullanıcı adın',
  'helper.profileEdit.fullNameLabel': 'Ad soyad',
  'helper.profileEdit.fullNamePlaceholder': 'Adını ve soyadını yaz',
  'helper.profileEdit.fullNameHint': 'Gerçek adın ve soyadın',
  'helper.profileEdit.phoneLabel': 'Telefon',
  'helper.profileEdit.phonePlaceholder': '+90 5xx xxx xx xx',
  'helper.profileEdit.phoneHint': 'İletişim numaran',
  'helper.profileEdit.dobLabel': 'Doğum tarihi',
  'helper.profileEdit.dobPlaceholder': '15-01-1990',
  'helper.profileEdit.dobHint': 'Format: GG-AA-YYYY',
  'helper.profileEdit.countryLabel': 'TC Kimlik No',
  'helper.profileEdit.countryPlaceholder': '11 haneli kimlik no',
  'helper.profileEdit.emailLabel': 'E-posta',
  'helper.profileEdit.emailHint': 'Kayıtlı e-posta adresin',
  'status.profileEdit.verified': 'Doğrulandı',
  'cta.profileEdit.edit': 'Düzenle',
  'headline.profileEdit.accountSection': 'Hesap bilgileri',
  'headline.profileEdit.securitySection': 'Şifre değiştir',
  'helper.profileEdit.forgotPasswordHint': 'Şifremi unuttum, e-postama doğrulama kodu gönder',
  'cta.profileEdit.sendResetCode': 'Kodu gönder',
  'helper.profileEdit.codeLabel': 'Doğrulama kodu',
  'helper.profileEdit.codePlaceholder': '6 haneli kod',
  'helper.profileEdit.newPasswordLabel': 'Yeni şifre',
  'helper.profileEdit.newPasswordPlaceholder': 'En az 8 karakter',
  'helper.profileEdit.newPasswordAgainLabel': 'Yeni şifre (tekrar)',
  'helper.profileEdit.newPasswordAgainPlaceholder': 'Yeni şifreyi tekrar yaz',
  'cta.profileEdit.changePassword': 'Şifreyi güncelle',
  'error.profileEdit.passwordRequired': 'Kod ve şifre alanlarını doldurman gerekiyor.',
  'error.profileEdit.passwordMin': 'Yeni şifre en az 8 karakter olmalı.',
  'error.profileEdit.passwordMismatch': 'Yeni şifreler aynı değil.',
  'error.profileEdit.codeRequired': 'Doğrulama kodunu girmen gerekiyor.',
  'status.profileEdit.resetCodeSent': 'Kod gönderildi. E-postanı kontrol et.',
  'status.profileEdit.buyer': 'Alıcı',
  'status.profileEdit.seller': 'Satıcı',
  'status.profileEdit.both': 'Alıcı & Satıcı',
  'helper.profileEdit.permissionTitle': 'İzin gerekiyor',
  'helper.profileEdit.permissionMessage': 'Galeriye erişim ver ki avatarını seçebilelim.',
  'error.profileEdit.imageType': 'Sadece JPEG, PNG veya WebP seç.',
  'error.profileEdit.imageUpload': 'Resmi şu an yükleyemedik.',
  'error.profileEdit.displayNameMin': 'Görünen isim en az 3 karakter olmalı.',
  'status.profileEdit.saved': 'Profilin güncellendi.',
  'cta.profileEdit.save': 'Kaydet',
  'helper.profileEdit.load': 'Profil şu an yüklenemedi.',
  'error.profileEdit.save': 'Profil şu an kaydedilemedi.',
  'helper.profileEdit.noDefaultAddress': 'Varsayılan adres yok',
  'helper.profileEdit.defaultAddressLoading': 'Varsayılan adres yükleniyor...',
  'headline.profileEdit.completeTitle': 'Profilini Tamamla',
  'error.profileEdit.fullNameRequired': 'Ad soyad zorunludur.',
  'error.profileEdit.phoneRequired': 'Telefon numarası zorunludur.',
  'error.profileEdit.dobRequired': 'Doğum tarihi zorunludur.',
  'error.profileEdit.dobFormat': 'Doğum tarihi formatı GG-AA-YYYY olmalı.',

  'headline.voice.disconnected': 'Bağlantı kesildi',
  'helper.voice.disconnected': 'Oturum kapandı. Ne yapmak istersin?',
  'cta.voice.end': 'Bitir',
  'cta.voice.cancel': 'Kapat',
  'error.voice.setupTitle': 'Ses ayarı tamamlanamadı',
  'status.voice.preparingTitle': 'Ses hazırlanıyor...',
  'helper.voice.preparingBody': 'Mikrofon ve hoparlör ayarlanıyor.',
  'error.voice.connectionTitle': 'Bağlantı kurulamadı',
  'error.voice.mediaAccess': 'Mikrofon erişimi şu an olmadı. İzinleri kontrol edip tekrar dene.',
  'cta.voice.back': 'Geri',
  'status.voice.connecting': 'Bağlanıyor...',
  'status.voice.reconnecting': 'Tekrar bağlanıyor...',
  'status.voice.disconnected': 'Bağlantı kesildi',
  'status.voice.speaking': 'Usta konuşuyor...',
  'status.voice.listening': 'Seni dinliyorum...',
  'helper.voice.subtitle': 'Ne yemek istediğini söyle',
  'status.voice.navAction': 'Sayfa açılıyor',
  'status.voice.addedAction': 'Yemek listene eklendi',
  'status.voice.orderSummaryAction': 'Yemek listen hazır',
  'error.home.favoriteUpdateFailed': 'Favori güncellenemedi. Tekrar dene.',

  'headline.settings.title': 'Güvenlik',
  'cta.settings.back': 'Geri',
  'cta.settings.done': 'Tamam',
  'helper.settings.securitySubtitle': 'Hesabının güvenliğini yönet',
  'helper.settings.passwordLastChanged': 'Son değiştirme: 2 ay önce',
  'helper.settings.twoFactorSubtitle': 'Ek güvenlik katmanı',
  'helper.settings.twoFactorComingSoon': 'Bu özellik yakında açılacak.',
  'headline.settings.whyImportant': 'Neden Önemli?',
  'helper.settings.whyImportantBody': 'Şifreni düzenli değiştirmen ve iki aşamalı doğrulamayı açman hesabını korur.',
  'headline.settings.connection': 'Bağlantı',
  'helper.settings.apiBaseUrl': 'API adresi',
  'cta.settings.saveConnection': 'Bağlantıyı kaydet',
  'cta.settings.saved': 'Kaydedildi',
  'headline.settings.aiServers': 'Yapay zeka sunucuları',
  'status.settings.agent': 'Asistan',
  'status.settings.language': 'Dil',
  'helper.settings.sttServer': 'STT sunucusu',
  'helper.settings.ttsServer': 'TTS sunucusu',
  'helper.settings.llmServer': 'LLM sunucusu',
  'cta.settings.saveServerSelection': 'Sunucu secimini kaydet',
  'helper.settings.noServers': 'Bu profilde sunucu bulunamadı. Admin panelinden STT/TTS/LLM ayarlarını yap.',
  'status.settings.disabled': 'pasif',
  'status.security.passwordTitle': 'Şifre',
  'status.security.emailVerification': 'E-posta Doğrulama',
  'status.security.phoneVerification': 'Telefon Doğrulama',
  'status.security.twoFactorTitle': 'İki Aşamalı Doğrulama',
  'status.security.off': 'Kapalı',
  'status.security.phoneFallback': '+90 5xx xxx xx xx',
  'cta.security.changePassword': 'Şifre Değiştir',
  'cta.security.changeEmail': 'E-posta Değiştir',
  'cta.security.changePhone': 'Telefon Numarasını Değiştir',
  'cta.security.enable': 'Etkinleştir',
  'error.settings.load': 'Sunucu ayarları yüklenemedi.',
  'error.settings.save': 'Kayıt şu an tamamlanamadı.',
  'headline.common.error': 'Hata',
  'headline.common.session': 'Oturum',
  'headline.common.success': 'Tamam',
  'headline.common.saved': 'Kaydedildi',
  'headline.common.warning': 'Uyarı',
  'headline.common.permission': 'İzin gerekli',
  'cta.common.goBack': 'Geri dön',
  'status.common.loading': 'Yükleniyor...',
  'error.common.mapOpenFailed': 'Harita açılamadı',
  'status.orders.loading': 'Siparişler yükleniyor...',
  'status.orders.error': 'Siparişler yüklenemedi',
  'headline.orders.complaintTitle': 'Şikayet Oluştur',
  'headline.orders.complaintEmptyTitle': 'Şikayet için sipariş bulunamadı',
  'helper.orders.complaintEmptySubtitle': 'Siparişlerin tamamlandığında buradan şikayet oluşturabilirsin.',
  'headline.chatList.title': 'Mesajlar',
  'status.chatList.loading': 'Mesajlar yükleniyor...',
  'headline.chatList.emptyTitle': 'Henüz mesajın yok',
  'helper.chatList.emptySubtitle': 'Satıcılarla mesajlaşmaya başladığında burada görünecek.',
  'helper.chatList.emptyPreview': 'Henüz mesaj yok',
  'helper.chat.inputPlaceholder': 'Mesajını yaz...',
  'headline.favorites.title': 'Favorilerim',
  'status.favorites.loading': 'Favoriler yükleniyor...',
  'headline.favorites.emptyTitle': 'Favori yemeğin yok',
  'helper.favorites.emptySubtitle': 'Beğendiğin yemekleri favorilere ekle, hızlıca ulaş.',
  'headline.notifications.title': 'Bildirimler',
  'status.notifications.loading': 'Bildirimler yükleniyor...',
  'headline.notifications.emptyTitle': 'Bildirim yok',
  'helper.notifications.emptySubtitle': 'Yeni bildirimlerini burada göreceksin.',
  'error.notifications.load': 'Bildirimler yüklenemedi',
  'status.notifications.justNow': 'Az önce',
  'status.notifications.minutesAgo': '{count} dk önce',
  'status.notifications.hoursAgo': '{count} saat önce',
  'status.notifications.daysAgo': '{count} gün önce',
  'status.notifications.month.0': 'Oca',
  'status.notifications.month.1': 'Şub',
  'status.notifications.month.2': 'Mar',
  'status.notifications.month.3': 'Nis',
  'status.notifications.month.4': 'May',
  'status.notifications.month.5': 'Haz',
  'status.notifications.month.6': 'Tem',
  'status.notifications.month.7': 'Ağu',
  'status.notifications.month.8': 'Eyl',
  'status.notifications.month.9': 'Eki',
  'status.notifications.month.10': 'Kas',
  'status.notifications.month.11': 'Ara',
  'headline.foodDetail.title': 'Yemek Detayı',
  'error.foodDetail.stockTitle': 'Stok yetersiz',
  'error.foodDetail.stockMessage': 'Bu üründen en fazla {stock} adet ekleyebilirsin.',
  'status.foodDetail.stockAvailable': '{stock} adet mevcut',
  'status.foodDetail.stockEmpty': 'Stok tükendi',
  'headline.foodDetail.seller': 'Satıcı',
  'cta.foodDetail.reviews': 'Yorumlar',
  'headline.orderDetail.title': 'Sipariş Detayı',
  'status.orderDetail.loading': 'Yükleniyor...',
  'error.orderDetail.notFound': 'Sipariş bulunamadı',
  'error.orderDetail.cancel': 'İptal edilemedi',
  'error.orderDetail.complete': 'Tamamlanamadı',
  'error.orderDetail.statusUpdate': 'Durum güncellenemedi',
  'helper.orderDetail.addressMissing': 'Adres bilgisi yok',
  'helper.orderDetail.pickupFallback': 'Satıcıdan teslim alınacak',
  'headline.deliveryPin.title': 'Teslimat Kodu',
  'status.deliveryPin.loading': 'Yükleniyor...',
  'headline.deliveryPin.pending': 'Kod bekleniyor',
  'helper.deliveryPin.pending': 'Satıcı sana bir kod gönderdi. Teslimat anında satıcıya bu kodu göster.',
  'headline.deliveryPin.verified': 'Kod doğrulandı',
  'helper.deliveryPin.verified': 'Teslimat başarıyla doğrulandı.',
  'headline.deliveryPin.failed': 'Kod doğrulanamadı',
  'helper.deliveryPin.failed': 'Çok fazla yanlış deneme yapıldı.',
  'headline.deliveryPin.expired': 'Kod süresi doldu',
  'helper.deliveryPin.expired': 'Kod süresi doldu. Satıcıdan yeni kod istemelisin.',
  'headline.deliveryPin.emptyTitle': 'Kod henüz gönderilmedi',
  'helper.deliveryPin.emptySubtitle': 'Satıcı teslimat kodunu gönderdikten sonra burada görünecek.',
  'helper.deliveryPin.codeLabel': 'Teslimat kodun',
  'helper.deliveryPin.codeHint': 'Bu kodu satıcıyla paylaş.',
  'helper.deliveryPin.attemptsRemaining': 'Deneme hakkı: {remaining} / 5',
  'headline.allergenDisclosure.title': 'Alerjen Bildirimi',
  'headline.allergenDisclosure.warningTitle': 'Alerjen Uyarısı',
  'helper.allergenDisclosure.warningBody': 'Bu siparişi tamamlayabilmek için alerjen bildirimini onaylaman gerekiyor. Eğer herhangi bir alerjenin varsa lütfen satıcıyla iletişime geç.',
  'status.allergenDisclosure.loading': 'Yükleniyor...',
  'headline.allergenDisclosure.records': 'Mevcut Kayıtlar',
  'status.allergenDisclosure.preOrder': 'Sipariş Öncesi',
  'status.allergenDisclosure.handover': 'Teslim Anı',
  'status.allergenDisclosure.acknowledged': 'Onaylandı',
  'status.allergenDisclosure.refused': 'Reddedildi',
  'cta.allergenDisclosure.acknowledge': 'Okudum, onaylıyorum',
  'cta.allergenDisclosure.refuse': 'Kabul etmiyorum',
  'headline.allergenDisclosure.acknowledgedTitle': 'Onaylandı',
  'helper.allergenDisclosure.acknowledgedBody': 'Alerjen bildirimi kaydedildi.',
  'headline.allergenDisclosure.refusedTitle': 'Kaydedildi',
  'helper.allergenDisclosure.refusedBody': 'Alerjen bildirimini reddettin.',
  'error.allergenDisclosure.submit': 'İşlem başarısız',
  'headline.review.title': 'Yorum',
  'headline.review.createTitle': 'Yorum Yap',
  'headline.review.submittedTitle': 'Yorumun gönderildi',
  'helper.review.submittedSubtitle': 'Değerlendirmen için teşekkürler!',
  'helper.review.ratingLabel': 'Bu siparişi nasıl buldun?',
  'helper.review.ratingHintEmpty': 'Yıldıza dokun',
  'helper.review.ratingHintBad': 'Kötü',
  'helper.review.ratingHintOkay': 'Orta',
  'helper.review.ratingHintGood': 'İyi',
  'helper.review.ratingHintGreat': 'Harika!',
  'helper.review.commentLabel': 'Yorumun',
  'helper.review.commentPlaceholder': 'Deneyimini paylaş...',
  'cta.review.submit': 'Gönder',
  'error.review.ratingRequiredTitle': 'Puan ver',
  'error.review.ratingRequiredMessage': 'Lütfen yıldız seçerek bir puan ver.',
  'error.review.submit': 'Yorum gönderilemedi',
  'headline.complaint.title': 'Şikayet',
  'headline.complaint.createTitle': 'Şikayet Oluştur',
  'headline.complaint.submittedTitle': 'Talebin açıldı',
  'helper.complaint.submittedSubtitle': 'Destek ekibi en kısa sürede dönüş yapacak.',
  'headline.complaint.categoryTitle': 'Şikayet Kategorisi',
  'helper.complaint.descriptionLabel': 'Açıklama',
  'helper.complaint.descriptionPlaceholder': 'Yaşadığın sorunu detaylıca anlat...',
  'cta.complaint.submit': 'Şikayeti Gönder',
  'label.complaint.categoryQuality': 'Yemek kalitesi',
  'label.complaint.categoryDelivery': 'Teslimat sorunu',
  'label.complaint.categoryWrongOrder': 'Yanlış sipariş',
  'label.complaint.categoryRefund': 'Ücret iadesi',
  'error.complaint.categoryRequiredTitle': 'Kategori seç',
  'error.complaint.categoryRequiredMessage': 'Lütfen bir şikayet kategorisi seç.',
  'error.complaint.descriptionRequiredTitle': 'Açıklama yaz',
  'error.complaint.descriptionRequiredMessage': 'Şikayetini en az 10 karakter ile açıkla.',
  'error.complaint.submit': 'Şikayet gönderilemedi',
  'headline.seller.home.greeting': 'Merhaba, {name} 👋',
  'status.seller.home.ratingCount': '({count} yorum)',
  'cta.seller.home.foodsManager': 'Yemek Yönetimi',
  'cta.seller.home.wallet': 'Cüzdanım',
  'headline.seller.home.todayOrders': 'Bugünkü Siparişler',
  'headline.seller.home.activeFoods': 'Satıştaki Yemekler',
  'headline.seller.home.emptyOrdersTitle': 'Aktif sipariş yok',
  'helper.seller.home.emptyOrdersSubtitle': 'Yeni sipariş geldiğinde burada görünecek.',
  'headline.seller.home.groupPreparing': 'Hazırlananlar',
  'headline.seller.home.groupRoute': 'Yolda / Kapıda',
  'headline.seller.home.groupDone': 'Tamamlananlar',
  'helper.seller.home.groupEmpty': 'Bu grupta sipariş yok.',
  'status.seller.home.new': 'Yeni',
  'status.seller.home.buyerOnWay': 'Alıcı: Yoldayım',
  'status.seller.home.buyerComing': 'Alıcı: Geliyorum',
  'status.seller.home.buyerAtDoor': 'Alıcı: Kapıdayım',
  'status.seller.home.noElapsed': 'Süre bilgisi yok',
  'status.seller.home.justArrived': 'Az önce geldi',
  'status.seller.home.minutesElapsed': '{count} dakika geçti',
  'status.seller.home.hoursElapsed': '{hours} saat {minutes} dakika geçti',
  'status.seller.home.daysElapsed': '{days} gün {hours} saat geçti',
  'status.seller.home.cancelled': 'İptal',
  'status.seller.home.pickupReady': 'Hazırlandı',
  'cta.seller.home.startPreparing': 'Hazırlıyorum',
  'cta.seller.home.markReady': 'Hazırlandı',
  'cta.seller.home.onTheWay': 'Yoldayım',
  'cta.seller.home.approaching': 'Yaklaştım',
  'cta.seller.home.atDoor': 'Kapıdayım',
  'cta.seller.home.leftForDelivery': 'Yola Çıktı',
  'cta.seller.home.verifyPin': 'Kodu Doğrula',
  'status.seller.home.processing': 'İşleniyor...',
  'cta.seller.home.switchToBuyer': 'Alıcı Moduna Geç',
  'headline.seller.home.emptyFoodsTitle': 'Satıştaki yemek yok',
  'helper.seller.home.emptyFoodsSubtitle': 'Yemek Yönetimi içinden yemek aktifleştirebilirsin.',
  'status.seller.home.active': 'Aktif',
  'status.seller.home.stockLine': 'Stok: {stock} adet',
  'error.seller.home.actionFailed': 'İşlem başarısız',

  'headline.seller.foodsManager.title': 'Yemek Düzenle',
  'cta.seller.foodsManager.addFood': 'Yemek Ekle',
  'status.seller.foodsManager.loading': 'Yemekler hazırlanıyor...',
  'status.seller.foodsManager.active': 'Aktif',
  'status.seller.foodsManager.passive': 'Pasif',
  'helper.seller.foodsManager.summaryMissing': 'Özet yok',
  'status.seller.foodsManager.stock': 'Stok: {stock}',
  'cta.seller.foodsManager.editFood': 'Yemeği Düzenle',
  'headline.seller.foodsManager.emptyTitle': 'Henüz yemek yok',
  'helper.seller.foodsManager.emptySubtitle': 'Yemek eklediğinde burada göreceksin.',
  'helper.seller.foodsManager.loadingSubtitle': 'Ekran hazır, içerik birkaç saniye içinde gelecek.',
  'error.seller.foodsManager.load': 'Yemekler yüklenemedi',

  'headline.seller.orders.title': 'Sipariş Yönetimi',
  'headline.seller.orders.filters': 'Filtreler',
  'helper.seller.orders.fromDate': 'Başlangıç (YYYY-MM-DD)',
  'helper.seller.orders.toDate': 'Bitiş (YYYY-MM-DD)',
  'headline.seller.orders.emptyTitle': 'Filtreye uygun sipariş bulunamadı',
  'helper.seller.orders.emptySubtitle': 'Bugüne ait siparişler ana sayfadaki Bugünkü Siparişler bölümünde kalır.',
  'helper.seller.orders.emptyErrorSubtitle': 'Bağlantıyı kontrol edip tekrar yenile.',
  'status.seller.orders.buyer': 'Alıcı: {name}',
  'error.seller.orders.load': 'Siparişler yüklenemedi',
  'status.seller.orders.month.0': 'Oca',
  'status.seller.orders.month.1': 'Şub',
  'status.seller.orders.month.2': 'Mar',
  'status.seller.orders.month.3': 'Nis',
  'status.seller.orders.month.4': 'May',
  'status.seller.orders.month.5': 'Haz',
  'status.seller.orders.month.6': 'Tem',
  'status.seller.orders.month.7': 'Ağu',
  'status.seller.orders.month.8': 'Eyl',
  'status.seller.orders.month.9': 'Eki',
  'status.seller.orders.month.10': 'Kas',
  'status.seller.orders.month.11': 'Ara',

  'headline.seller.profileEdit.title': 'Profili Düzenle',
  'helper.seller.profile.defaultAddress': 'Varsayılan adres',
  'cta.seller.profile.editAddress': 'Adresi düzenle',
  'helper.seller.profile.kitchenTitle': 'Mutfak başlığı',
  'helper.seller.profile.kitchenTitlePlaceholder': "Örn: İsmet'in Ev Mutfağı",
  'helper.seller.profile.kitchenDescription': 'Mutfak açıklaması',
  'helper.seller.profile.kitchenDescriptionPlaceholder': 'Yemek tarzını ve servis yapını anlat.',
  'helper.seller.profile.deliveryRadius': 'Teslimat yarıçapı (km)',
  'helper.seller.profile.deliveryRadiusPlaceholder': 'Örn: 5',
  'helper.seller.profile.notAdded': 'Henüz eklenmedi',
  'helper.seller.profile.deliverySettings': 'Teslimat ayarı',
  'status.seller.profile.deliveryOpen': 'Teslimat açık',
  'status.seller.profile.deliveryClosed': 'Teslimat kapalı',
  'helper.seller.profile.deliveryOpenHint': 'Sipariş bazında teslimat teklif edebilirsin.',
  'helper.seller.profile.deliveryClosedHint': 'Siparişler varsayılan olarak Gel Al kalır.',
  'helper.seller.profile.deliveryTerms': 'Teslimat koşulları',
  'helper.seller.profile.deliveryTermsPlaceholder': "Örn: 3 km içi, apartman kapısına teslim, akşam 21:00'e kadar.",
  'helper.seller.profile.workingHours': 'Çalışma saatleri',
  'cta.seller.profile.submitReview': 'İncelemeye Gönder',
  'cta.seller.profile.save': 'Kaydet',
  'helper.seller.profile.noDefaultAddress': 'Varsayılan adres yok',
  'error.seller.profile.load': 'Profil yüklenemedi',
  'error.seller.profile.save': 'Kaydedilemedi',
  'status.seller.profile.sentToReview': 'Profil incelemeye gönderildi.',
  'status.seller.profile.saved': 'Profil kaydedildi.',

  'headline.seller.profileDetail.title': 'Satıcı Profili',
  'cta.seller.profileDetail.retry': 'Tekrar Dene',
  'cta.seller.profileDetail.logout': 'Çıkış Yap',
  'headline.seller.profileDetail.compliance': 'Belge Durumu',
  'status.seller.profileDetail.completed': 'Tamamlanan: {done}/{total}',
  'cta.seller.profileDetail.openDocuments': 'Belgeleri aç',
  'headline.seller.profileDetail.editProfile': 'Profili Düzenle',
  'headline.seller.profileDetail.deliverySettings': 'Teslimat Ayarı',
  'label.seller.profileDetail.delivery': 'Teslimat',
  'label.seller.profileDetail.radius': 'Yarıçap',
  'label.seller.profileDetail.terms': 'Koşullar',
  'cta.seller.profileDetail.tapToEdit': 'Düzenlemek için dokun',
  'headline.seller.profileDetail.about': 'Hakkımda',
  'cta.seller.profileDetail.orderHistory': 'Sipariş Geçmişim',
  'cta.seller.profileDetail.reviews': 'Yorumlar / Değerlendirmeler',
  'cta.seller.profileDetail.settings': 'Ayarlar',
  'headline.seller.profileDetail.workingHours': 'Çalışma Saatleri',

  'headline.seller.foods.titleAdd': 'Yemek Ekle',
  'headline.seller.foods.titleEdit': 'Yemek Düzenle',
  'status.seller.foods.preparingEdit': 'Yemek düzenleme ekranı hazırlanıyor...',
  'headline.seller.foods.photos': 'Yemek Fotoğrafları',
  'cta.seller.foods.addPhoto': 'Resim Ekle',
  'helper.seller.foods.photoHint': '(Tak/Çek/Kamera)',
  'headline.seller.foods.name': 'Yemek Adı *',
  'helper.seller.foods.namePlaceholder': 'Örn: Ev Yapımı Mantı',
  'headline.seller.foods.cuisine': 'Hangi Ülke/Şehir Mutfağı',
  'helper.seller.foods.cuisinePlaceholder': 'Örn: Türkiye mutfağı',
  'headline.seller.foods.category': 'Kategori Seç',
  'helper.seller.foods.categoryPlaceholder': 'Kategori seçin',
  'headline.seller.foods.sideItems': 'Yemekle gelen yan ürünler',
  'helper.seller.foods.sideItemsPlaceholder': 'Örn: Ayran, salata, pilav',
  'headline.seller.foods.ingredients': 'Malzemeler / Baharatlar *',
  'helper.seller.foods.ingredientsPlaceholder': 'Kullanılan malzemeler ve baharatları açıklayın...',
  'headline.seller.foods.recipe': 'Tarif',
  'helper.seller.foods.recipePlaceholder': 'Yemeğin hazırlanış tarifini buraya yazın...',
  'headline.seller.foods.paidAddons': 'Ücretli Ekler',
  'helper.seller.foods.productNamePlaceholder': 'Ürün adı',
  'helper.seller.foods.pricePlaceholder': 'Ücret (₺)',
  'cta.seller.foods.add': '+ Ekle',
  'headline.seller.foods.allergens': 'Alerjenler',
  'helper.seller.foods.allergensPlaceholder': 'Örn: Gluten, süt (yoksa: yok)',
  'headline.seller.foods.price': 'Fiyat (₺) *',
  'headline.seller.foods.dailyStock': 'Günlük Stok *',
  'helper.seller.foods.dailyStockPlaceholder': 'Örn: 10',
  'headline.seller.foods.prepTime': 'Hazırlık Süresi (dk)',
  'helper.seller.foods.prepTimePlaceholder': 'Örn: 45',
  'headline.seller.foods.startDate': 'Başlangıç Tarihi',
  'headline.seller.foods.endDate': 'Bitiş Tarihi',
  'cta.seller.foods.preview': 'Önizleme (Müşteri Görünümü)',
  'status.seller.foods.publishing': 'Yayınlanıyor...',
  'cta.seller.foods.publishNew': 'Yemeği Yayınla',
  'cta.seller.foods.publishEdit': 'Güncelle ve Yayınla',
  'cta.seller.foods.clearEdit': 'Düzenlemeyi Temizle',
  'headline.seller.foods.customerPreview': 'Müşteri Görünümü',
  'headline.seller.foods.previewPhoto': 'Fotoğraf Önizleme',
  'label.seller.foods.allergenPrefix': 'Alerjen: {value}',
  'cta.seller.foods.keepEditing': 'Düzenlemeye Devam Et',
  'headline.seller.foods.freeAddons': 'Ücretsiz Ekler',
  'headline.seller.foods.paidAddonGroup': 'Ücretli {group}',
  'helper.seller.foods.emptyAddonGroup': 'Bu grupta kayıtlı ek yok.',
  'cta.seller.foods.addNewAddon': 'Yeni ek ekle',
  'headline.seller.foods.selectCategory': 'Kategori Seç',
  'helper.seller.foods.categoryMissing': 'Kategori bulunamadı. Yeniden dene.',
  'cta.seller.foods.refresh': 'Yenile',
  'label.seller.foods.kindSauce': 'Soslar',
  'label.seller.foods.kindExtra': 'Ek Gıdalar',
  'label.seller.foods.kindAppetizer': 'Aparatifler',
  'status.seller.foods.stockMissing': 'Stok girilmedi',
  'status.seller.foods.defaultCuisine': 'Ev Mutfağı',
  'error.seller.foods.serverHtml': 'Sunucu JSON yerine HTML döndürdü. Lütfen tekrar dene.',
  'error.seller.foods.load': 'Yemekler yüklenemedi',
  'error.seller.foods.categoriesLoad': 'Kategoriler yüklenemedi',
  'error.seller.foods.editTargetMissing': 'Düzenlenecek yemek bulunamadı.',
  'error.seller.foods.galleryPermission': 'Albümden fotoğraf seçmek için galeri izni vermelisin.',
  'error.seller.foods.imageDataMissing': 'Fotoğraf verisi alınamadı.',
  'error.seller.foods.imagePick': 'Fotoğraf seçilemedi.',
  'error.seller.foods.nameRequired': 'Yemek adı zorunlu.',
  'error.seller.foods.categoryRequired': 'Kategori seçimi zorunlu.',
  'error.seller.foods.cuisineRequired': 'Hangi ülke/şehir mutfağı alanı zorunlu.',
  'error.seller.foods.ingredientsRequired': 'Malzemeler / baharatlar alanı zorunlu.',
  'error.seller.foods.recipeRequired': 'Tarif alanı zorunlu.',
  'error.seller.foods.allergensRequired': "Alerjen alanı zorunlu. Yoksa 'yok' yaz.",
  'error.seller.foods.priceRequired': 'Fiyat zorunlu.',
  'error.seller.foods.stockRequired': "Günlük stok zorunlu ve 0'dan büyük olmalı.",
  'error.seller.foods.prepRequired': "Hazırlık süresi zorunlu ve 0'dan büyük olmalı.",
  'error.seller.foods.datesRequired': 'Başlangıç ve bitiş tarihi zorunlu.',
  'error.seller.foods.endDateInvalid': 'Bitiş tarihi başlangıç tarihinden sonra olmalı.',
  'error.seller.foods.addonsRequired': 'Ekler bölümünde en az 1 kalem olmalı.',
  'error.seller.foods.paidAddonPrice': "Ücretli eklerde fiyat 0'dan büyük olmalı.",
  'error.seller.foods.statusUpdate': 'Yemek durumu güncellenemedi',
  'error.seller.foods.lotCreate': 'Lot oluşturulamadı',
  'error.seller.foods.save': 'Yemek kaydedilemedi',
  'status.seller.foods.publishDateFixedTitle': 'Yanlış tarihtesin',
  'status.seller.foods.publishDateFixedBody': 'Geçmiş veya hatalı tarih girdin. Sistem satış tarihini otomatik düzeltti.',
  'status.seller.foods.publishedTitle': 'Başarılı',
  'status.seller.foods.publishedBodyNew': 'Yemek yayınlandı.',
  'status.seller.foods.publishedBodyEdit': 'Yemek güncellenip yayınlandı.',
  'status.seller.foods.savedBodyNew': 'Yemek kaydedildi.',
  'status.seller.foods.savedBodyEdit': 'Yemek güncellendi.',
  'error.seller.foods.addonNameRequired': 'Ek adı zorunlu.',
  'error.seller.foods.addonDuplicate': 'Aynı ek tekrar eklenemez.',
  'error.seller.foods.addonPriceRequired': 'Ücretli ek için fiyat zorunlu.',
  'status.seller.foods.addonExistsTitle': 'Bilgi',
  'status.seller.foods.addonExistsBody': 'Bu ek zaten seçili.',
} as const;

export type BrandCopyKey = keyof typeof brandCopy;

type SupportedLocale = 'tr' | 'en';

const brandCopyEn: Partial<Record<BrandCopyKey, string>> = {
  'helper.home.stockLimitMessage': 'You can add only the remaining portions to your list.',
  'helper.home.cartEmptyTitle': 'Your food list is empty right now.',
  'headline.home.pendingListTitle': 'Your list has been sent',
  'helper.home.pendingListSubtitle': 'It is now pending. You will get a notification once the cook confirms the plan.',
  'cta.home.cartCheckout': 'Ask the cook',
  'helper.home.cartCheckoutHint': 'This sends your food list to the cook. We will let you know once the plan is confirmed.',
  'cta.home.backHome': 'Back to home',
  'status.home.paymentTitle': 'Table status',
  'status.home.orderLabel': 'List:',
  'status.home.orderStatusLabel': 'Status:',
  'status.home.paymentDone': 'Payment completed',
  'status.home.paymentWaiting': 'Waiting for seller approval',
  'status.home.orderStatus.pending_seller_approval': 'Waiting for seller approval',
  'status.home.orderStatus.seller_approved': 'Seller confirmed',
  'status.home.orderStatus.awaiting_payment': 'Collecting payment',
  'status.home.orderStatus.preparing': 'Preparing',
  'status.home.orderStatus.ready': 'Ready',
  'status.home.orderStatus.in_delivery': 'On the way',
  'status.home.orderStatus.at_door': 'At the door',
  'status.home.orderStatus.delivered': 'Delivered',
  'status.home.orderStatus.completed': 'Delivered',
  'status.home.orderStatus.cancelled': 'Cancelled',
  'status.home.orderStatus.rejected': 'Cancelled',
  'status.home.paymentAttempt.initiated': 'Payment started',
  'status.home.paymentAttempt.pending': 'Payment pending',
  'status.home.paymentAttempt.processing': 'Payment processing',
  'status.home.paymentAttempt.succeeded': 'Payment successful',
  'status.home.paymentAttempt.failed': 'Payment failed',
  'status.home.paymentAttempt.canceled': 'Payment canceled',
  'status.home.paymentAttempt.requires_action': 'Payment action required',
  'headline.orders.activeTitle': 'Your latest order',
  'helper.orders.activeSubtitle': 'It is not completed yet. Open details to see the latest status.',
  'headline.orders.completedTitle': 'Completed orders',
  'helper.orders.completedSubtitle': 'Your delivered orders stay here.',
  'headline.orders.preparingTitle': 'Pending / Preparing',
  'headline.orders.routeTitle': 'On the way / At the door',
  'headline.orders.historyTitle': 'Order history',
  'headline.orders.title': 'My orders',
  'headline.orders.emptyTitle': 'No orders yet',
  'helper.orders.emptySubtitle': 'Your orders will appear here after you place one.',
  'headline.orders.quickActiveTitle': 'Your latest order',
  'helper.orders.quickPendingSubtitle': 'Your order is with the seller. You can check the status here quickly.',
  'helper.orders.quickPreparingSubtitle': 'Your order is moving forward. You can track the latest status here.',
  'helper.orders.searchPlaceholder': 'Search seller, meal, or order no...',
  'helper.orders.searchEmptyTitle': 'No matching order found',
  'helper.orders.searchEmptySubtitle': 'Try a different word.',
  'helper.orders.completedEmptyTitle': 'No completed order yet',
  'helper.orders.completedEmptySubtitle': 'Your delivered orders will appear here.',
  'helper.orders.loading': 'Loading orders...',
  'error.orders.load': 'Orders could not be loaded',
  'helper.orders.groupEmpty': 'There is no order in this group.',
  'status.orders.sellerFallback': 'Seller',
  'helper.orders.itemsFallback': 'Order items',
  'status.orders.countSuffix': 'orders',
  'cta.orders.openDetail': 'Open details',
  'status.orders.deliveryType.delivery': 'Delivery',
  'status.orders.deliveryType.pickup': 'Pickup',
  'status.orders.activePill': 'Active',
  'status.orders.completedPill': 'History',
  'status.orders.newBadge': 'New',
  'cta.orders.viewAll': 'Show all my orders',
  'status.home.notificationsTitle': 'Notifications',
  'helper.home.notificationsEmpty': 'You will see your new notifications here.',
  'status.home.messagesTitle': 'Messages',
  'helper.home.messagesSubtitle': 'Chat quickly with sellers',
  'headline.home.profileSellerTitle': 'Would you like to cook and sell from home?',
  'helper.home.profileSellerBody': 'Turn your kitchen into income on Coziyoo.',
  'cta.home.becomeSeller': 'Become a seller',
  'headline.home.generalSettingsTitle': 'General settings',
  'helper.home.generalSettingsBody': 'You can change the app language here.',
  'helper.home.generalSettingsLanguageLabel': 'Language',
  'helper.home.generalSettingsLanguageHint': 'For now, Turkish and English are supported.',
  'cta.home.languageTurkish': 'Türkçe',
  'cta.home.languageEnglish': 'English',
  'cta.home.addToCart': 'Add to list',
  'helper.home.cartEmptyAlertTitle': 'Your food list is empty',
  'helper.home.cartEmptyAlertMessage': 'Let’s add a meal to your list first.',
  'error.home.payableLotsMissing': 'There are no available items left to send from your food list.',
  'headline.home.foodListTitle': 'Food List',
  'status.home.foodListCountSuffix': 'items',
  'helper.home.flowTitle': 'Table plan',
  'helper.home.flowStartTypeLabel': 'Starting plan',
  'helper.home.pickupAddressLabel': 'Pickup address',
  'helper.home.flowNoteLabel': 'Quick note',
  'helper.home.flowDefaultPickupNote': 'Your food list goes to the seller first. If suitable, they can offer delivery later.',
  'helper.home.pickupAddressLoading': 'Seller address is loading...',
  'helper.home.pickupAddressMissing': 'Seller address could not be found.',
  'error.home.pickupAddressFailed': 'Seller address could not be loaded.',
  'helper.home.paymentCapturePendingSingle': 'Your list has been sent to the cook. It is now pending. You will get a notification once the cook confirms.',
  'helper.home.paymentCapturePendingMultiple': 'Your list has been sent to the cooks. It is now pending. You will get notifications as cooks confirm.',
  'helper.home.paymentCaptureDoneSingle': 'Payment completed! Your list has been sent to the seller.',
  'helper.home.paymentProgress': '{completed}/{total} payments completed.',
  'helper.home.flowSellerMissing': 'Seller information is missing.',
  'cta.home.requestDelivery': 'Request delivery',
  'helper.home.deliveryRequestPending': 'Your delivery request has been sent to the seller.',
  'helper.home.deliveryRequestSuccess': 'Your delivery request has been sent to the seller.',
  'error.home.deliveryRequestFailed': 'Delivery request could not be sent.',
  'error.home.checkoutCreateFailed': 'The list could not be sent.',
  'error.home.checkoutMissingOrderId': 'The list identifier did not return.',
  'error.home.checkoutStartFailed': 'The table flow could not be started.',
  'helper.seller.orderDetail.deliveryRequestTitle': 'Buyer requested delivery',
  'helper.seller.orderDetail.deliveryRequestBody': 'This order started as pickup, but the buyer asked for delivery. If you can do it, choose delivery and approve. If not, keep it as pickup.',
  'cta.seller.orderDetail.canDeliver': 'I can deliver',
  'cta.seller.orderDetail.keepPickup': 'Keep pickup',
  'cta.seller.orderDetail.approveDelivery': 'Approve delivery and collect payment',
  'cta.seller.orderDetail.approvePickup': 'Approve as pickup',
  'error.home.paymentStatusFailed': 'Payment status could not be loaded.',
  'helper.home.toastAddedToList': 'Added to your food list',
  'helper.home.allergenTitle': 'Allergen warning',
  'helper.home.allergenConfirm': 'This meal contains these allergens:\n\n🔴 {allergens}\n\nDo you still want to add it to your list?',
  'cta.home.addAnyway': 'Add anyway',
  'headline.home.processingTitle': 'Your table is being prepared',
  'helper.home.processingCreateList': 'Preparing your list...',
  'helper.home.processingCapturePayment': 'Collecting payment...',
  'helper.home.processingSendSeller': 'Sending to seller...',
  'helper.home.processingDone': 'Done!',
  'headline.home.processingSuccess': 'Your table is ready!',
  'headline.home.tabHome': 'Home',
  'headline.home.tabMessages': 'Messages',
  'headline.home.tabOrders': 'Orders',
  'headline.home.tabNotifications': 'Notifications',
  'status.voice.addedAction': 'Added to your food list',
  'status.voice.orderSummaryAction': 'Your food list is ready',
  'headline.common.error': 'Error',
  'headline.common.session': 'Session',
  'headline.common.success': 'Done',
  'headline.common.saved': 'Saved',
  'headline.common.warning': 'Warning',
  'headline.common.permission': 'Permission required',
  'cta.common.goBack': 'Go back',
  'status.common.loading': 'Loading...',
  'error.common.mapOpenFailed': 'Map could not be opened',
  'status.orders.loading': 'Loading orders...',
  'status.orders.error': 'Orders could not be loaded',
  'headline.orders.complaintTitle': 'Create Complaint',
  'headline.orders.complaintEmptyTitle': 'No order found for complaint',
  'helper.orders.complaintEmptySubtitle': 'You can create a complaint here once your orders are completed.',
  'headline.chatList.title': 'Messages',
  'status.chatList.loading': 'Loading messages...',
  'headline.chatList.emptyTitle': 'You do not have any messages yet',
  'helper.chatList.emptySubtitle': 'They will appear here once you start chatting with sellers.',
  'helper.chatList.emptyPreview': 'No messages yet',
  'helper.chat.inputPlaceholder': 'Write your message...',
  'headline.favorites.title': 'My Favorites',
  'status.favorites.loading': 'Loading favorites...',
  'headline.favorites.emptyTitle': 'You do not have a favorite meal yet',
  'helper.favorites.emptySubtitle': 'Add meals you like to favorites for quick access.',
  'headline.notifications.title': 'Notifications',
  'status.notifications.loading': 'Loading notifications...',
  'headline.notifications.emptyTitle': 'No notifications',
  'helper.notifications.emptySubtitle': 'You will see your new notifications here.',
  'error.notifications.load': 'Notifications could not be loaded',
  'status.notifications.justNow': 'Just now',
  'status.notifications.minutesAgo': '{count} min ago',
  'status.notifications.hoursAgo': '{count} hr ago',
  'status.notifications.daysAgo': '{count} day ago',
  'status.notifications.month.0': 'Jan',
  'status.notifications.month.1': 'Feb',
  'status.notifications.month.2': 'Mar',
  'status.notifications.month.3': 'Apr',
  'status.notifications.month.4': 'May',
  'status.notifications.month.5': 'Jun',
  'status.notifications.month.6': 'Jul',
  'status.notifications.month.7': 'Aug',
  'status.notifications.month.8': 'Sep',
  'status.notifications.month.9': 'Oct',
  'status.notifications.month.10': 'Nov',
  'status.notifications.month.11': 'Dec',
  'headline.foodDetail.title': 'Meal Details',
  'error.foodDetail.stockTitle': 'Not enough stock',
  'error.foodDetail.stockMessage': 'You can add at most {stock} of this item.',
  'status.foodDetail.stockAvailable': '{stock} available',
  'status.foodDetail.stockEmpty': 'Out of stock',
  'headline.foodDetail.seller': 'Seller',
  'cta.foodDetail.reviews': 'Reviews',
  'headline.orderDetail.title': 'Order Details',
  'status.orderDetail.loading': 'Loading...',
  'error.orderDetail.notFound': 'Order could not be found',
  'error.orderDetail.cancel': 'Could not be canceled',
  'error.orderDetail.complete': 'Could not be completed',
  'error.orderDetail.statusUpdate': 'Status could not be updated',
  'helper.orderDetail.addressMissing': 'Address information is missing',
  'helper.orderDetail.pickupFallback': 'You will pick it up from the seller',
  'headline.deliveryPin.title': 'Delivery Code',
  'status.deliveryPin.loading': 'Loading...',
  'headline.deliveryPin.pending': 'Code pending',
  'helper.deliveryPin.pending': 'The seller sent you a code. Show this code to the seller at delivery.',
  'headline.deliveryPin.verified': 'Code verified',
  'helper.deliveryPin.verified': 'The delivery was verified successfully.',
  'headline.deliveryPin.failed': 'Code could not be verified',
  'helper.deliveryPin.failed': 'Too many wrong attempts were made.',
  'headline.deliveryPin.expired': 'Code expired',
  'helper.deliveryPin.expired': 'The code has expired. You should ask the seller for a new code.',
  'headline.deliveryPin.emptyTitle': 'Code has not been sent yet',
  'helper.deliveryPin.emptySubtitle': 'It will appear here once the seller sends the delivery code.',
  'helper.deliveryPin.codeLabel': 'Your delivery code',
  'helper.deliveryPin.codeHint': 'Share this code with the seller.',
  'helper.deliveryPin.attemptsRemaining': 'Attempts left: {remaining} / 5',
  'headline.allergenDisclosure.title': 'Allergen Disclosure',
  'headline.allergenDisclosure.warningTitle': 'Allergen Warning',
  'helper.allergenDisclosure.warningBody': 'You need to confirm the allergen disclosure to complete this order. If you have any allergens, please contact the seller.',
  'status.allergenDisclosure.loading': 'Loading...',
  'headline.allergenDisclosure.records': 'Existing Records',
  'status.allergenDisclosure.preOrder': 'Before order',
  'status.allergenDisclosure.handover': 'At handover',
  'status.allergenDisclosure.acknowledged': 'Confirmed',
  'status.allergenDisclosure.refused': 'Rejected',
  'cta.allergenDisclosure.acknowledge': 'I read it, I confirm',
  'cta.allergenDisclosure.refuse': 'I do not accept',
  'headline.allergenDisclosure.acknowledgedTitle': 'Confirmed',
  'helper.allergenDisclosure.acknowledgedBody': 'The allergen disclosure has been saved.',
  'headline.allergenDisclosure.refusedTitle': 'Saved',
  'helper.allergenDisclosure.refusedBody': 'You rejected the allergen disclosure.',
  'error.allergenDisclosure.submit': 'Action failed',
  'headline.review.title': 'Review',
  'headline.review.createTitle': 'Write Review',
  'headline.review.submittedTitle': 'Your review was sent',
  'helper.review.submittedSubtitle': 'Thanks for your feedback!',
  'helper.review.ratingLabel': 'How was this order?',
  'helper.review.ratingHintEmpty': 'Tap a star',
  'helper.review.ratingHintBad': 'Bad',
  'helper.review.ratingHintOkay': 'Okay',
  'helper.review.ratingHintGood': 'Good',
  'helper.review.ratingHintGreat': 'Great!',
  'helper.review.commentLabel': 'Your review',
  'helper.review.commentPlaceholder': 'Share your experience...',
  'cta.review.submit': 'Send',
  'error.review.ratingRequiredTitle': 'Give a rating',
  'error.review.ratingRequiredMessage': 'Please choose a star rating.',
  'error.review.submit': 'Review could not be sent',
  'headline.profileEdit.completeTitle': 'Complete Your Profile',
  'error.profileEdit.fullNameRequired': 'Full name is required.',
  'error.profileEdit.phoneRequired': 'Phone number is required.',
  'error.profileEdit.dobRequired': 'Date of birth is required.',
  'error.profileEdit.dobFormat': 'Date of birth must be in DD-MM-YYYY format.',
  'error.home.favoriteUpdateFailed': 'Favorite could not be updated. Please try again.',
  'headline.complaint.title': 'Complaint',
  'headline.complaint.createTitle': 'Create Complaint',
  'headline.complaint.submittedTitle': 'Your request was opened',
  'helper.complaint.submittedSubtitle': 'The support team will get back to you soon.',
  'headline.complaint.categoryTitle': 'Complaint Category',
  'helper.complaint.descriptionLabel': 'Description',
  'helper.complaint.descriptionPlaceholder': 'Explain the issue you experienced in detail...',
  'cta.complaint.submit': 'Send Complaint',
  'label.complaint.categoryQuality': 'Meal quality',
  'label.complaint.categoryDelivery': 'Delivery issue',
  'label.complaint.categoryWrongOrder': 'Wrong order',
  'label.complaint.categoryRefund': 'Refund',
  'error.complaint.categoryRequiredTitle': 'Choose a category',
  'error.complaint.categoryRequiredMessage': 'Please choose a complaint category.',
  'error.complaint.descriptionRequiredTitle': 'Write a description',
  'error.complaint.descriptionRequiredMessage': 'Please explain your complaint in at least 10 characters.',
  'error.complaint.submit': 'Complaint could not be sent',
  'headline.seller.home.greeting': 'Hello, {name} 👋',
  'status.seller.home.ratingCount': '({count} reviews)',
  'cta.seller.home.foodsManager': 'Food Manager',
  'cta.seller.home.wallet': 'My Wallet',
  'headline.seller.home.todayOrders': "Today's Orders",
  'headline.seller.home.activeFoods': 'Foods on Sale',
  'headline.seller.home.emptyOrdersTitle': 'No active orders',
  'helper.seller.home.emptyOrdersSubtitle': 'They will appear here when a new order arrives.',
  'headline.seller.home.groupPreparing': 'Preparing',
  'headline.seller.home.groupRoute': 'On the way / At door',
  'headline.seller.home.groupDone': 'Completed',
  'helper.seller.home.groupEmpty': 'There are no orders in this group.',
  'status.seller.home.new': 'New',
  'status.seller.home.buyerOnWay': 'Buyer: On my way',
  'status.seller.home.buyerComing': 'Buyer: Coming',
  'status.seller.home.buyerAtDoor': 'Buyer: At the door',
  'status.seller.home.noElapsed': 'No time data',
  'status.seller.home.justArrived': 'Arrived just now',
  'status.seller.home.minutesElapsed': '{count} minutes passed',
  'status.seller.home.hoursElapsed': '{hours} hours {minutes} minutes passed',
  'status.seller.home.daysElapsed': '{days} days {hours} hours passed',
  'status.seller.home.cancelled': 'Cancelled',
  'status.seller.home.pickupReady': 'Ready',
  'cta.seller.home.startPreparing': 'Preparing',
  'cta.seller.home.markReady': 'Ready',
  'cta.seller.home.onTheWay': 'On my way',
  'cta.seller.home.approaching': 'Approaching',
  'cta.seller.home.atDoor': 'At the door',
  'cta.seller.home.leftForDelivery': 'Left for delivery',
  'cta.seller.home.verifyPin': 'Verify Code',
  'status.seller.home.processing': 'Processing...',
  'cta.seller.home.switchToBuyer': 'Switch to Buyer',
  'headline.seller.home.emptyFoodsTitle': 'No food on sale',
  'helper.seller.home.emptyFoodsSubtitle': 'You can activate foods from Food Manager.',
  'status.seller.home.active': 'Active',
  'status.seller.home.stockLine': 'Stock: {stock}',
  'error.seller.home.actionFailed': 'Action failed',
  'headline.seller.foodsManager.title': 'Edit Food',
  'cta.seller.foodsManager.addFood': 'Add Food',
  'status.seller.foodsManager.loading': 'Preparing foods...',
  'status.seller.foodsManager.active': 'Active',
  'status.seller.foodsManager.passive': 'Passive',
  'helper.seller.foodsManager.summaryMissing': 'No summary',
  'status.seller.foodsManager.stock': 'Stock: {stock}',
  'cta.seller.foodsManager.editFood': 'Edit Food',
  'headline.seller.foodsManager.emptyTitle': 'No food yet',
  'helper.seller.foodsManager.emptySubtitle': 'You will see it here once you add food.',
  'helper.seller.foodsManager.loadingSubtitle': 'The screen is ready, content will arrive in a few seconds.',
  'error.seller.foodsManager.load': 'Foods could not be loaded',
  'headline.seller.orders.title': 'Order Management',
  'headline.seller.orders.filters': 'Filters',
  'helper.seller.orders.fromDate': 'Start (YYYY-MM-DD)',
  'helper.seller.orders.toDate': 'End (YYYY-MM-DD)',
  'headline.seller.orders.emptyTitle': 'No orders match this filter',
  'helper.seller.orders.emptySubtitle': "Today's orders stay in the Today's Orders section on the home page.",
  'helper.seller.orders.emptyErrorSubtitle': 'Check the connection and refresh again.',
  'status.seller.orders.buyer': 'Buyer: {name}',
  'error.seller.orders.load': 'Orders could not be loaded',
  'status.seller.orders.month.0': 'Jan',
  'status.seller.orders.month.1': 'Feb',
  'status.seller.orders.month.2': 'Mar',
  'status.seller.orders.month.3': 'Apr',
  'status.seller.orders.month.4': 'May',
  'status.seller.orders.month.5': 'Jun',
  'status.seller.orders.month.6': 'Jul',
  'status.seller.orders.month.7': 'Aug',
  'status.seller.orders.month.8': 'Sep',
  'status.seller.orders.month.9': 'Oct',
  'status.seller.orders.month.10': 'Nov',
  'status.seller.orders.month.11': 'Dec',
  'headline.seller.profileEdit.title': 'Edit Profile',
  'helper.seller.profile.defaultAddress': 'Default address',
  'cta.seller.profile.editAddress': 'Edit address',
  'helper.seller.profile.kitchenTitle': 'Kitchen title',
  'helper.seller.profile.kitchenTitlePlaceholder': "For example: Ismet's Home Kitchen",
  'helper.seller.profile.kitchenDescription': 'Kitchen description',
  'helper.seller.profile.kitchenDescriptionPlaceholder': 'Describe your food style and service.',
  'helper.seller.profile.deliveryRadius': 'Delivery radius (km)',
  'helper.seller.profile.deliveryRadiusPlaceholder': 'For example: 5',
  'helper.seller.profile.notAdded': 'Not added yet',
  'helper.seller.profile.deliverySettings': 'Delivery setting',
  'status.seller.profile.deliveryOpen': 'Delivery on',
  'status.seller.profile.deliveryClosed': 'Delivery off',
  'helper.seller.profile.deliveryOpenHint': 'You can offer delivery per order.',
  'helper.seller.profile.deliveryClosedHint': 'Orders stay as pickup by default.',
  'helper.seller.profile.deliveryTerms': 'Delivery terms',
  'helper.seller.profile.deliveryTermsPlaceholder': 'For example: within 3 km, apartment entrance delivery, until 21:00.',
  'helper.seller.profile.workingHours': 'Working hours',
  'cta.seller.profile.submitReview': 'Send for Review',
  'cta.seller.profile.save': 'Save',
  'helper.seller.profile.noDefaultAddress': 'No default address',
  'error.seller.profile.load': 'Profile could not be loaded',
  'error.seller.profile.save': 'Could not be saved',
  'status.seller.profile.sentToReview': 'Profile was sent for review.',
  'status.seller.profile.saved': 'Profile was saved.',
  'headline.seller.profileDetail.title': 'Seller Profile',
  'cta.seller.profileDetail.retry': 'Retry',
  'cta.seller.profileDetail.logout': 'Log out',
  'headline.seller.profileDetail.compliance': 'Document Status',
  'status.seller.profileDetail.completed': 'Completed: {done}/{total}',
  'cta.seller.profileDetail.openDocuments': 'Open documents',
  'headline.seller.profileDetail.editProfile': 'Edit Profile',
  'headline.seller.profileDetail.deliverySettings': 'Delivery Setting',
  'label.seller.profileDetail.delivery': 'Delivery',
  'label.seller.profileDetail.radius': 'Radius',
  'label.seller.profileDetail.terms': 'Terms',
  'cta.seller.profileDetail.tapToEdit': 'Tap to edit',
  'headline.seller.profileDetail.about': 'About me',
  'cta.seller.profileDetail.orderHistory': 'My Order History',
  'cta.seller.profileDetail.reviews': 'Reviews / Ratings',
  'cta.seller.profileDetail.settings': 'Settings',
  'headline.seller.profileDetail.workingHours': 'Working Hours',
  'headline.seller.foods.titleAdd': 'Add Food',
  'headline.seller.foods.titleEdit': 'Edit Food',
  'status.seller.foods.preparingEdit': 'Preparing the food edit screen...',
  'headline.seller.foods.photos': 'Food Photos',
  'cta.seller.foods.addPhoto': 'Add Photo',
  'helper.seller.foods.photoHint': '(Upload/Take/Camera)',
  'headline.seller.foods.name': 'Food Name *',
  'helper.seller.foods.namePlaceholder': 'For example: Homemade Manti',
  'headline.seller.foods.cuisine': 'Which Country/City Cuisine',
  'helper.seller.foods.cuisinePlaceholder': 'For example: Turkish cuisine',
  'headline.seller.foods.category': 'Choose Category',
  'helper.seller.foods.categoryPlaceholder': 'Choose category',
  'headline.seller.foods.sideItems': 'Items that come with the meal',
  'helper.seller.foods.sideItemsPlaceholder': 'For example: Ayran, salad, rice',
  'headline.seller.foods.ingredients': 'Ingredients / Spices *',
  'helper.seller.foods.ingredientsPlaceholder': 'Explain the ingredients and spices used...',
  'headline.seller.foods.recipe': 'Recipe',
  'helper.seller.foods.recipePlaceholder': 'Write how the meal is prepared here...',
  'headline.seller.foods.paidAddons': 'Paid Add-ons',
  'helper.seller.foods.productNamePlaceholder': 'Product name',
  'helper.seller.foods.pricePlaceholder': 'Price (₺)',
  'cta.seller.foods.add': '+ Add',
  'headline.seller.foods.allergens': 'Allergens',
  'helper.seller.foods.allergensPlaceholder': 'For example: Gluten, milk (if none: none)',
  'headline.seller.foods.price': 'Price (₺) *',
  'headline.seller.foods.dailyStock': 'Daily Stock *',
  'helper.seller.foods.dailyStockPlaceholder': 'For example: 10',
  'headline.seller.foods.prepTime': 'Preparation Time (min)',
  'helper.seller.foods.prepTimePlaceholder': 'For example: 45',
  'headline.seller.foods.startDate': 'Start Date',
  'headline.seller.foods.endDate': 'End Date',
  'cta.seller.foods.preview': 'Preview (Customer View)',
  'status.seller.foods.publishing': 'Publishing...',
  'cta.seller.foods.publishNew': 'Publish Food',
  'cta.seller.foods.publishEdit': 'Update and Publish',
  'cta.seller.foods.clearEdit': 'Clear Edit',
  'headline.seller.foods.customerPreview': 'Customer View',
  'headline.seller.foods.previewPhoto': 'Photo Preview',
  'label.seller.foods.allergenPrefix': 'Allergen: {value}',
  'cta.seller.foods.keepEditing': 'Keep Editing',
  'headline.seller.foods.freeAddons': 'Free Add-ons',
  'headline.seller.foods.paidAddonGroup': 'Paid {group}',
  'helper.seller.foods.emptyAddonGroup': 'There are no saved add-ons in this group.',
  'cta.seller.foods.addNewAddon': 'Add new add-on',
  'headline.seller.foods.selectCategory': 'Choose Category',
  'helper.seller.foods.categoryMissing': 'Category could not be found. Try again.',
  'cta.seller.foods.refresh': 'Refresh',
  'label.seller.foods.kindSauce': 'Sauces',
  'label.seller.foods.kindExtra': 'Extras',
  'label.seller.foods.kindAppetizer': 'Appetizers',
  'status.seller.foods.stockMissing': 'Stock not entered',
  'status.seller.foods.defaultCuisine': 'Home Kitchen',
  'error.seller.foods.serverHtml': 'Server returned HTML instead of JSON. Please try again.',
  'error.seller.foods.load': 'Foods could not be loaded',
  'error.seller.foods.categoriesLoad': 'Categories could not be loaded',
  'error.seller.foods.editTargetMissing': 'Food to edit could not be found.',
  'error.seller.foods.galleryPermission': 'You need to allow gallery access to choose a photo.',
  'error.seller.foods.imageDataMissing': 'Photo data could not be read.',
  'error.seller.foods.imagePick': 'Photo could not be selected.',
  'error.seller.foods.nameRequired': 'Food name is required.',
  'error.seller.foods.categoryRequired': 'Category selection is required.',
  'error.seller.foods.cuisineRequired': 'Country/city cuisine field is required.',
  'error.seller.foods.ingredientsRequired': 'Ingredients / spices field is required.',
  'error.seller.foods.recipeRequired': 'Recipe field is required.',
  'error.seller.foods.allergensRequired': "Allergen field is required. If none, write 'none'.",
  'error.seller.foods.priceRequired': 'Price is required.',
  'error.seller.foods.stockRequired': 'Daily stock is required and must be greater than 0.',
  'error.seller.foods.prepRequired': 'Preparation time is required and must be greater than 0.',
  'error.seller.foods.datesRequired': 'Start and end date are required.',
  'error.seller.foods.endDateInvalid': 'End date must be after start date.',
  'error.seller.foods.addonsRequired': 'Add-ons section must have at least 1 item.',
  'error.seller.foods.paidAddonPrice': 'Paid add-ons must have a price greater than 0.',
  'error.seller.foods.statusUpdate': 'Food status could not be updated',
  'error.seller.foods.lotCreate': 'Lot could not be created',
  'error.seller.foods.save': 'Food could not be saved',
  'status.seller.foods.publishDateFixedTitle': 'Wrong date',
  'status.seller.foods.publishDateFixedBody': 'You entered a past or invalid date. The system fixed the sale date automatically.',
  'status.seller.foods.publishedTitle': 'Success',
  'status.seller.foods.publishedBodyNew': 'Food was published.',
  'status.seller.foods.publishedBodyEdit': 'Food was updated and published.',
  'status.seller.foods.savedBodyNew': 'Food was saved.',
  'status.seller.foods.savedBodyEdit': 'Food was updated.',
  'error.seller.foods.addonNameRequired': 'Add-on name is required.',
  'error.seller.foods.addonDuplicate': 'The same add-on cannot be added twice.',
  'error.seller.foods.addonPriceRequired': 'A price is required for a paid add-on.',
  'status.seller.foods.addonExistsTitle': 'Info',
  'status.seller.foods.addonExistsBody': 'This add-on is already selected.',
};

const HOME_SUBTITLE_GENERIC_VARIANTS = [
  'Bugün ne yemek istersin?',
  'Canın ne çekiyorsa ona bakalım.',
  'Sana güzel bir şey öneririm.',
  'En çok satanlara bir göz atalım mı?',
  'Birlikte hızlıca bir şey seçelim mi?',
  'Bence bugün kendini güzel bir yemekle şımart.',
] as const;

const HOME_SUBTITLE_DAYPART_VARIANTS = {
  morning: [
    'Kahvaltıda ne istersin?',
    'Kahvaltını yaptın mı, acıktın mı?',
    'Sana mis gibi bir kahvaltı öneririm.',
    'Bugün hafif mi gidelim, doyurucu mu?',
  ],
  noon: [
    'Ne yemek istersin, beraber seçelim.',
    'Sana şimdi iyi gidecek bir şey öneririm.',
    'Öğlen acıktın mı, ne yiyelim?',
    'Bir tık ev yemeği moduna geçelim mi?',
  ],
  evening: [
    'Canın ne istiyorsa ona gidelim.',
    'Sana sıcacık bir şey öneririm.',
    'Akşam yemeği için ne düşünüyorsun?',
    'Bugün menüyü beraber toparlayalım mı?',
  ],
} as const;

export function t(key: BrandCopyKey): string {
  if (getCurrentLanguage() === 'en') {
    return brandCopyEn[key] ?? brandCopy[key];
  }
  return brandCopy[key];
}

export function formatCopy(
  key: BrandCopyKey,
  values: Record<string, string | number>,
): string {
  return Object.entries(values).reduce(
    (message, [token, value]) => message.replace(new RegExp(`\\{${token}\\}`, 'g'), String(value)),
    t(key),
  );
}

export function randomHomeGreetingSubtitle(date = new Date()): string {
  const hour = date.getHours();
  const dayPart =
    hour < 11
      ? 'morning'
      : hour < 17
        ? 'noon'
        : 'evening';

  const pool = [
    ...HOME_SUBTITLE_DAYPART_VARIANTS[dayPart],
    ...HOME_SUBTITLE_GENERIC_VARIANTS,
  ];

  return pool[Math.floor(Math.random() * pool.length)] ?? 'Bugün ne yesek?';
}

export function stockLine(totalStock: number, remainingStock: number): string {
  return `${remainingStock} ${t('status.home.stockLineSuffix')} ${t('helper.home.stockLinePrefix')}`;
}

export function requestErrorLine(status: number): string {
  return `${t('error.home.requestFailed')} (${status})`;
}
