export const brandCopy = {
  'headline.home.greetingTitle': 'Günaydın, Lale',
  'headline.home.greetingSubtitle': 'Bugün ne yesek?',
  'headline.home.slogan': 'Komşunun mutfağından, kapına.',
  'helper.home.sloganSubline': 'Yakınındaki ev şeflerinden sıcacık yemekler',
  'helper.home.searchPlaceholder': 'Yemek ya da usta ara...',
  'helper.home.stockLimitTitle': 'Stok sınırı',
  'helper.home.stockLimitMessage': 'Bu yemekten kalan kadar listene ekleyebilirsin.',
  'helper.home.stockLinePrefix': 'kaldı',
  'status.home.stockLineSuffix': 'porsiyon',
  'helper.home.cartEmptyTitle': 'Yemek listen şu an boş.',
  'headline.home.pendingListTitle': 'Listen şefe iletildi',
  'helper.home.pendingListSubtitle': 'Şu an beklemede. Şef planı onaylayınca sana bildirim gelecektir.',
  'cta.home.cartCheckout': 'Şefe sor',
  'helper.home.cartCheckoutHint': 'Bu buton yemek listeni şefe gönderir. Şef planı netleştirince sana haber veririz.',
  'cta.home.paymentRefresh': 'Durumu yenile',
  'cta.home.paymentNext': 'Sonraki ödeme',
  'status.home.paymentTitle': 'Sofra durumu',
  'status.home.orderLabel': 'Liste:',
  'status.home.orderStatusLabel': 'Durum:',
  'status.home.paymentDone': 'Ödeme tamamlandı',
  'status.home.paymentWaiting': 'Satıcı onayı bekleniyor',
  'status.home.orderStatus.pending_seller_approval': 'Satıcı onayı bekleniyor',
  'status.home.orderStatus.seller_approved': 'Usta onayladı',
  'status.home.orderStatus.awaiting_payment': 'Ödeme alınıyor',
  'status.home.orderStatus.preparing': 'Hazırlanıyor',
  'status.home.orderStatus.ready': 'Hazır',
  'status.home.orderStatus.in_delivery': 'Yolda',
  'status.home.orderStatus.at_door': 'Kapıda',
  'status.home.orderStatus.delivered': 'Teslim Edildi',
  'status.home.orderStatus.completed': 'Teslim Edildi',
  'status.home.orderStatus.cancelled': 'İptal edildi',
  'status.home.orderStatus.rejected': 'İptal edildi',
  'status.home.paymentAttempt.initiated': 'Ödeme başlatıldı',
  'status.home.paymentAttempt.pending': 'Ödeme beklemede',
  'status.home.paymentAttempt.processing': 'Ödeme işleniyor',
  'status.home.paymentAttempt.succeeded': 'Ödeme başarılı',
  'status.home.paymentAttempt.failed': 'Ödeme başarısız',
  'status.home.paymentAttempt.canceled': 'Ödeme iptal edildi',
  'status.home.paymentAttempt.requires_action': 'Ödeme işlemi gerekiyor',
  'status.home.notificationsTitle': 'Bildirimler',
  'helper.home.notificationsEmpty': 'Yeni bildirimlerini burada göreceksin.',
  'status.home.messagesTitle': 'Mesajlar',
  'helper.home.messagesSubtitle': 'Ustalarla hızlıca yazış',
  'helper.home.messageInputPlaceholder': 'Mesajını yaz...',
  'status.home.profileTitle': 'Profil',
  'cta.home.profileEdit': 'Profili düzenle',
  'cta.home.myOrders': 'Siparişlerim',
  'helper.home.myOrdersHint': 'Geçmiş ve aktif siparişlerini gör',
  'cta.home.addresses': 'Adreslerim',
  'cta.home.deliveryAddressChange': 'Teslimat adresi değiştir',
  'helper.home.deliveryAddressHint': 'Siparişlerin bu adrese gider. Farklı yere geçtiysen buradan güncelle.',
  'cta.home.settings': 'Ayarlar',
  'cta.home.security': 'Güvenlik',
  'cta.home.logout': 'Çıkış yap',
  'headline.home.profileSellerTitle': 'Evinde yemek yapıp satmak ister misin?',
  'helper.home.profileSellerBody': "Coziyoo'da mutfağını gelire dönüştür.",
  'cta.home.becomeSeller': 'Satıcı Ol',
  'status.home.paymentWebTitle': 'Ödeme ekranı',
  'cta.home.close': 'Kapat',
  'error.home.paymentModuleMissing': 'Uygulama içi ödeme modülü bulunamadı.',
  'cta.home.openInBrowser': 'Tarayıcıda aç',
  'error.home.checkoutMissing': 'Ödeme bağlantısı şu an bulunamıyor.',
  'cta.home.addToCart': 'Listeye ekle',
  'status.home.sellerKitchen': 'Usta Mutfağı',
  'status.home.sellerReviews': 'Yorumlar',
  'status.home.sellerReviewsLoading': 'Yorumlar yükleniyor...',
  'helper.home.sellerReviewsEmpty': 'Bu usta için henüz yorum yok.',
  'helper.home.sellerCommentFallback': 'Yorum bırakılmamış.',
  'status.home.sellerMeals': 'Ustanın yemekleri',
  'status.home.agentTitle': 'Mutfak asistanı',
  'cta.home.retry': 'Tekrar dene',
  'status.home.connecting': 'Bağlanıyor...',
  'helper.home.agentInputPlaceholder': 'Mesajını yaz...',
  'error.home.serverUnavailable502': 'Mutfak tarafında kısa bir yoğunluk var (502). Birazdan tekrar dene.',
  'error.home.serverUnavailable503': 'Sunucu şu an meşgul (503). Birazdan tekrar dene.',
  'error.home.serverTimeout504': 'Sunucu geç cevap veriyor (504). Birazdan tekrar dene.',
  'error.home.serverGeneric': 'Sunucuda bir sorun var.',
  'error.home.requestFailed': 'Bir sorun oldu.',
  'error.home.unexpectedResponse': 'Sunucudan beklenmeyen bir cevap geldi.',
  'error.home.noMealsInResponse': 'Şu an yemek listesi alınmıyor.',
  'error.home.retryLater': 'Şu an ulaşılamıyor. Lütfen tekrar dene.',
  'error.home.sessionExpired': 'Oturumun bitmiş. Tekrar giriş yap.',
  'helper.home.cartEmptyAlertTitle': 'Yemek listen boş',
  'helper.home.cartEmptyAlertMessage': 'Önce listene bir yemek ekleyelim.',
  'error.home.payableLotsMissing': 'Yemek listende gönderilecek ürün kalmadı.',
  'helper.home.checkoutDeliveryType': 'Teslimat tipi',
  'cta.home.delivery': 'Teslimat',
  'cta.home.pickup': 'Gel Al',
  'helper.home.checkoutAddress': 'Teslimat adresi',
  'cta.home.changeAddress': 'Adresi değiştir',
  'cta.home.manageAddresses': 'Adreslerimi yönet',
  'helper.home.noDefaultAddress': 'Varsayılan adresin yok. Devam etmek için adres seç.',
  'helper.home.addressRequiredCheckout': 'Teslimat için önce adres seçmelisin.',
  'helper.home.locationDisabledUsingAddress': 'Konumun kapalı, adresine göre hesaplıyorum.',
  'helper.home.addressRequiredTopSold': 'Yakın usta için önce bir adres seçmelisin.',
  'helper.home.addressGeocodeFailed': 'Adresinden konum belirleyemedim. Adresi kontrol edip tekrar dene.',
  'helper.home.noNearbyTopSold': 'Üzgünüm, bu yemek senin yakınında değil.',
  'status.home.locationBasisLive': 'Canlı konum',
  'status.home.locationBasisAddressPrefix': 'Adres:',
  'headline.home.selectAddress': 'Teslimat adresi seç',
  'helper.home.selectAddressSubtitle': 'Bu sipariş için kayıtlı bir adres seç.',
  'helper.home.addressListEmpty': 'Kayıtlı adres bulunamadı.',
  'headline.home.foodListTitle': 'Yemek Listesi',
  'status.home.foodListCountSuffix': 'yemek',
  'helper.home.flowTitle': 'Sofra planı',
  'helper.home.flowStartTypeLabel': 'Başlangıç planı',
  'helper.home.pickupAddressLabel': 'Alım adresi',
  'helper.home.flowNoteLabel': 'Kısa not',
  'helper.home.flowDefaultPickupNote': 'Yemek listen önce satıcıya gider. Satıcı isterse sonradan teslimat teklif edebilir.',
  'helper.home.pickupAddressLoading': 'Satıcı adresi yükleniyor...',
  'helper.home.pickupAddressMissing': 'Satıcı adresi bulunamadı.',
  'error.home.pickupAddressFailed': 'Satıcı adresi alınamadı.',
  'helper.home.paymentCapturePendingSingle': 'Listen şefe gönderildi. Şu an beklemede. Şef onay verince sana bildirim gelecektir.',
  'helper.home.paymentCapturePendingMultiple': 'Listen şeflere gönderildi. Şu an beklemede. Şefler onay verdikçe sana bildirim gelecektir.',
  'helper.home.paymentCaptureDoneSingle': 'Ödeme tamamlandı! Listen satıcıya iletildi.',
  'helper.home.paymentProgress': '{completed}/{total} ödeme tamamlandı.',
  'helper.home.flowSellerMissing': 'Satıcı bilgisi eksik.',
  'error.home.checkoutCreateFailed': 'Liste gönderilemedi.',
  'error.home.checkoutMissingOrderId': 'Liste kimliği dönmedi.',
  'error.home.checkoutStartFailed': 'Sofra akışı başlatılamadı.',
  'error.home.paymentStatusFailed': 'Ödeme durumu alınamadı.',
  'helper.home.toastAddedToList': 'Yemek listene eklendi',
  'helper.home.allergenTitle': 'Alerjen uyarısı',
  'helper.home.allergenConfirm': 'Bu yemek şu alerjenleri içeriyor:\n\n🔴 {allergens}\n\nYine de listene eklemek istiyor musun?',
  'cta.home.addAnyway': 'Yine de ekle',
  'headline.home.processingTitle': 'Sofra hazırlanıyor',
  'helper.home.processingCreateList': 'Liste hazırlanıyor...',
  'helper.home.processingCapturePayment': 'Ödeme alınıyor...',
  'helper.home.processingSendSeller': 'Satıcıya iletiliyor...',
  'helper.home.processingDone': 'Tamamlandı!',
  'headline.home.processingSuccess': 'Sofran hazır!',
  'headline.home.tabHome': 'Ana Sayfa',
  'headline.home.tabMessages': 'Mesajlar',
  'headline.home.tabOrders': 'Orders',
  'headline.home.tabNotifications': 'Bildirim',

  'headline.login.title': 'Coziyoo',
  'headline.login.subtitle': 'Komşunun mutfağından sıcacık yemeklere hoş geldin',
  'helper.login.emailLabel': 'E-posta',
  'helper.login.emailPlaceholder': 'ornek@mail.com',
  'helper.login.passwordLabel': 'Şifre',
  'helper.login.passwordPlaceholder': '••••••••',
  'cta.login.signIn': 'Giriş yap',
  'cta.login.quickBuyerSignIn': 'Alıcı giriş',
  'cta.login.quickSellerSignIn': 'Satıcı giriş',
  'cta.login.tryAgain': 'Tekrar dene',
  'error.login.invalidCredentials': 'E-posta ya da şifre doğru değil.',
  'error.login.accountLocked': 'Hesabın kilitli. E-postandaki linkle tekrar açabilirsin.',
  'error.login.tooManyAttempts': 'Çok hızlı deneme yaptın. Biraz bekleyip tekrar dene.',
  'error.login.generic': 'Giriş şu an tamamlanamadı.',
  'error.login.emailRequired': 'E-posta yazman gerekiyor.',
  'error.login.passwordRequired': 'Şifre yazman gerekiyor.',
  'error.login.unexpectedResponse': 'Beklenmeyen bir cevap geldi.',
  'error.login.network': 'Bağlantı sorunu var. İnternetini kontrol edip tekrar dene.',

  'headline.address.title': 'Adreslerim',
  'cta.address.retry': 'Tekrar dene',
  'headline.address.emptyTitle': 'Henüz adres eklemedin',
  'helper.address.emptySubtitle': 'Sipariş için önce bir teslimat adresi ekleyelim.',
  'cta.address.add': 'Adres ekle',
  'status.address.default': 'Varsayılan',
  'cta.address.setDefault': 'Varsayılan yap',
  'headline.address.edit': 'Adresi düzenle',
  'headline.address.new': 'Yeni adres',
  'helper.address.titleLabel': 'Adres başlığı',
  'helper.address.titlePlaceholder': 'Ev, iş, aile...',
  'helper.address.addressLabel': 'Açık adres',
  'helper.address.addressPlaceholder': 'Mahalle, sokak, bina, daire...',
  'helper.address.defaultToggle': 'Bunu varsayılan adres yap',
  'cta.address.update': 'Kaydet',
  'cta.address.save': 'Kaydet',
  'error.address.load': 'Adreslerini şu an yükleyemedik.',
  'error.address.titleRequired': 'Adres başlığı boş olamaz.',
  'error.address.addressTooShort': 'Adres en az 3 karakter olmalı.',
  'error.address.save': 'Adresi şu an kaydedemedik.',
  'error.address.delete': 'Adres şu an silinemedi.',
  'error.address.default': 'Varsayılan adres şu an değiştirilemedi.',
  'helper.address.deleteTitle': 'Adresi sil',
  'helper.address.deleteMessage': 'Bu adresi silmek istediğine emin misin?',
  'cta.address.cancel': 'Vazgeç',
  'cta.address.delete': 'Sil',

  'headline.profileEdit.title': 'Profili düzenle',
  'helper.profileEdit.displayNameLabel': 'Görünen isim',
  'helper.profileEdit.displayNamePlaceholder': 'Adın nasıl görünsün?',
  'helper.profileEdit.displayNameHint': 'Uygulamada görünen adın',
  'helper.profileEdit.usernameLabel': 'Kullanıcı adı',
  'helper.profileEdit.usernamePlaceholder': 'lezzetduragi',
  'helper.profileEdit.usernameHint': 'Benzersiz @kullanıcı adın',
  'helper.profileEdit.fullNameLabel': 'Ad soyad',
  'helper.profileEdit.fullNamePlaceholder': 'Adını ve soyadını yaz',
  'helper.profileEdit.fullNameHint': 'Gerçek adın ve soyadın',
  'helper.profileEdit.phoneLabel': 'Telefon',
  'helper.profileEdit.phonePlaceholder': '+90 5xx xxx xx xx',
  'helper.profileEdit.phoneHint': 'İletişim numaran',
  'helper.profileEdit.dobLabel': 'Doğum tarihi',
  'helper.profileEdit.dobPlaceholder': '15-01-1990',
  'helper.profileEdit.dobHint': 'Format: GG-AA-YYYY',
  'helper.profileEdit.countryLabel': 'TC Kimlik No',
  'helper.profileEdit.countryPlaceholder': '11 haneli kimlik no',
  'helper.profileEdit.emailLabel': 'E-posta',
  'helper.profileEdit.emailHint': 'Kayıtlı e-posta adresin',
  'status.profileEdit.verified': 'Doğrulandı',
  'cta.profileEdit.edit': 'Düzenle',
  'headline.profileEdit.accountSection': 'Hesap bilgileri',
  'headline.profileEdit.securitySection': 'Şifre değiştir',
  'helper.profileEdit.forgotPasswordHint': 'Şifremi unuttum, e-postama doğrulama kodu gönder',
  'cta.profileEdit.sendResetCode': 'Kodu gönder',
  'helper.profileEdit.codeLabel': 'Doğrulama kodu',
  'helper.profileEdit.codePlaceholder': '6 haneli kod',
  'helper.profileEdit.newPasswordLabel': 'Yeni şifre',
  'helper.profileEdit.newPasswordPlaceholder': 'En az 8 karakter',
  'helper.profileEdit.newPasswordAgainLabel': 'Yeni şifre (tekrar)',
  'helper.profileEdit.newPasswordAgainPlaceholder': 'Yeni şifreyi tekrar yaz',
  'cta.profileEdit.changePassword': 'Şifreyi güncelle',
  'error.profileEdit.passwordRequired': 'Kod ve şifre alanlarını doldurman gerekiyor.',
  'error.profileEdit.passwordMin': 'Yeni şifre en az 8 karakter olmalı.',
  'error.profileEdit.passwordMismatch': 'Yeni şifreler aynı değil.',
  'error.profileEdit.codeRequired': 'Doğrulama kodunu girmen gerekiyor.',
  'status.profileEdit.resetCodeSent': 'Kod gönderildi. E-postanı kontrol et.',
  'status.profileEdit.buyer': 'Alıcı',
  'status.profileEdit.seller': 'Satıcı',
  'status.profileEdit.both': 'Alıcı & Satıcı',
  'helper.profileEdit.permissionTitle': 'İzin gerekiyor',
  'helper.profileEdit.permissionMessage': 'Galeriye erişim ver ki avatarını seçebilelim.',
  'error.profileEdit.imageType': 'Sadece JPEG, PNG veya WebP seç.',
  'error.profileEdit.imageUpload': 'Resmi şu an yükleyemedik.',
  'error.profileEdit.displayNameMin': 'Görünen isim en az 3 karakter olmalı.',
  'status.profileEdit.saved': 'Profilin güncellendi.',
  'cta.profileEdit.save': 'Kaydet',
  'helper.profileEdit.load': 'Profil şu an yüklenemedi.',
  'error.profileEdit.save': 'Profil şu an kaydedilemedi.',
  'helper.profileEdit.noDefaultAddress': 'Varsayılan adres yok',
  'helper.profileEdit.defaultAddressLoading': 'Varsayılan adres yükleniyor...',

  'headline.voice.disconnected': 'Bağlantı kesildi',
  'helper.voice.disconnected': 'Oturum kapandı. Ne yapmak istersin?',
  'cta.voice.end': 'Bitir',
  'cta.voice.cancel': 'Kapat',
  'error.voice.setupTitle': 'Ses ayarı tamamlanamadı',
  'status.voice.preparingTitle': 'Ses hazırlanıyor...',
  'helper.voice.preparingBody': 'Mikrofon ve hoparlör ayarlanıyor.',
  'error.voice.connectionTitle': 'Bağlantı kurulamadı',
  'error.voice.mediaAccess': 'Mikrofon erişimi şu an olmadı. İzinleri kontrol edip tekrar dene.',
  'cta.voice.back': 'Geri',
  'status.voice.connecting': 'Bağlanıyor...',
  'status.voice.reconnecting': 'Tekrar bağlanıyor...',
  'status.voice.disconnected': 'Bağlantı kesildi',
  'status.voice.speaking': 'Usta konuşuyor...',
  'status.voice.listening': 'Seni dinliyorum...',
  'helper.voice.subtitle': 'Ne yemek istediğini söyle',
  'status.voice.navAction': 'Sayfa açılıyor',
  'status.voice.addedAction': 'Yemek listene eklendi',
  'status.voice.orderSummaryAction': 'Yemek listen hazır',

  'headline.settings.title': 'Güvenlik',
  'cta.settings.back': 'Geri',
  'cta.settings.done': 'Tamam',
  'helper.settings.securitySubtitle': 'Hesabının güvenliğini yönet',
  'helper.settings.passwordLastChanged': 'Son değiştirme: 2 ay önce',
  'helper.settings.twoFactorSubtitle': 'Ek güvenlik katmanı',
  'helper.settings.twoFactorComingSoon': 'Bu özellik yakında açılacak.',
  'headline.settings.whyImportant': 'Neden Önemli?',
  'helper.settings.whyImportantBody': 'Şifreni düzenli değiştirmen ve iki aşamalı doğrulamayı açman hesabını korur.',
  'headline.settings.connection': 'Bağlantı',
  'helper.settings.apiBaseUrl': 'API adresi',
  'cta.settings.saveConnection': 'Bağlantıyı kaydet',
  'cta.settings.saved': 'Kaydedildi',
  'headline.settings.aiServers': 'Yapay zeka sunucuları',
  'status.settings.agent': 'Asistan',
  'status.settings.language': 'Dil',
  'helper.settings.sttServer': 'STT sunucusu',
  'helper.settings.ttsServer': 'TTS sunucusu',
  'helper.settings.llmServer': 'LLM sunucusu',
  'cta.settings.saveServerSelection': 'Sunucu secimini kaydet',
  'helper.settings.noServers': 'Bu profilde sunucu bulunamadı. Admin panelinden STT/TTS/LLM ayarlarını yap.',
  'status.settings.disabled': 'pasif',
  'status.security.passwordTitle': 'Şifre',
  'status.security.emailVerification': 'E-posta Doğrulama',
  'status.security.phoneVerification': 'Telefon Doğrulama',
  'status.security.twoFactorTitle': 'İki Aşamalı Doğrulama',
  'status.security.off': 'Kapalı',
  'status.security.phoneFallback': '+90 5xx xxx xx xx',
  'cta.security.changePassword': 'Şifre Değiştir',
  'cta.security.changeEmail': 'E-posta Değiştir',
  'cta.security.changePhone': 'Telefon Numarasını Değiştir',
  'cta.security.enable': 'Etkinleştir',
  'error.settings.load': 'Sunucu ayarları yüklenemedi.',
  'error.settings.save': 'Kayıt şu an tamamlanamadı.',
} as const;

export type BrandCopyKey = keyof typeof brandCopy;

type SupportedLocale = 'tr' | 'en';

const brandCopyEn: Partial<Record<BrandCopyKey, string>> = {
  'helper.home.stockLimitMessage': 'You can add only the remaining portions to your list.',
  'helper.home.cartEmptyTitle': 'Your food list is empty right now.',
  'headline.home.pendingListTitle': 'Your list has been sent',
  'helper.home.pendingListSubtitle': 'It is now pending. You will get a notification once the cook confirms the plan.',
  'cta.home.cartCheckout': 'Ask the cook',
  'helper.home.cartCheckoutHint': 'This sends your food list to the cook. We will let you know once the plan is confirmed.',
  'status.home.paymentTitle': 'Table status',
  'status.home.orderLabel': 'List:',
  'status.home.orderStatusLabel': 'Status:',
  'status.home.paymentDone': 'Payment completed',
  'status.home.paymentWaiting': 'Waiting for seller approval',
  'status.home.orderStatus.pending_seller_approval': 'Waiting for seller approval',
  'status.home.orderStatus.seller_approved': 'Seller confirmed',
  'status.home.orderStatus.awaiting_payment': 'Collecting payment',
  'status.home.orderStatus.preparing': 'Preparing',
  'status.home.orderStatus.ready': 'Ready',
  'status.home.orderStatus.in_delivery': 'On the way',
  'status.home.orderStatus.at_door': 'At the door',
  'status.home.orderStatus.delivered': 'Delivered',
  'status.home.orderStatus.completed': 'Delivered',
  'status.home.orderStatus.cancelled': 'Cancelled',
  'status.home.orderStatus.rejected': 'Cancelled',
  'status.home.paymentAttempt.initiated': 'Payment started',
  'status.home.paymentAttempt.pending': 'Payment pending',
  'status.home.paymentAttempt.processing': 'Payment processing',
  'status.home.paymentAttempt.succeeded': 'Payment successful',
  'status.home.paymentAttempt.failed': 'Payment failed',
  'status.home.paymentAttempt.canceled': 'Payment canceled',
  'status.home.paymentAttempt.requires_action': 'Payment action required',
  'status.home.notificationsTitle': 'Notifications',
  'helper.home.notificationsEmpty': 'You will see your new notifications here.',
  'status.home.messagesTitle': 'Messages',
  'helper.home.messagesSubtitle': 'Chat quickly with sellers',
  'cta.home.addToCart': 'Add to list',
  'helper.home.cartEmptyAlertTitle': 'Your food list is empty',
  'helper.home.cartEmptyAlertMessage': 'Let’s add a meal to your list first.',
  'error.home.payableLotsMissing': 'There are no available items left to send from your food list.',
  'headline.home.foodListTitle': 'Food List',
  'status.home.foodListCountSuffix': 'items',
  'helper.home.flowTitle': 'Table plan',
  'helper.home.flowStartTypeLabel': 'Starting plan',
  'helper.home.pickupAddressLabel': 'Pickup address',
  'helper.home.flowNoteLabel': 'Quick note',
  'helper.home.flowDefaultPickupNote': 'Your food list goes to the seller first. If suitable, they can offer delivery later.',
  'helper.home.pickupAddressLoading': 'Seller address is loading...',
  'helper.home.pickupAddressMissing': 'Seller address could not be found.',
  'error.home.pickupAddressFailed': 'Seller address could not be loaded.',
  'helper.home.paymentCapturePendingSingle': 'Your list has been sent to the cook. It is now pending. You will get a notification once the cook confirms.',
  'helper.home.paymentCapturePendingMultiple': 'Your list has been sent to the cooks. It is now pending. You will get notifications as cooks confirm.',
  'helper.home.paymentCaptureDoneSingle': 'Payment completed! Your list has been sent to the seller.',
  'helper.home.paymentProgress': '{completed}/{total} payments completed.',
  'helper.home.flowSellerMissing': 'Seller information is missing.',
  'error.home.checkoutCreateFailed': 'The list could not be sent.',
  'error.home.checkoutMissingOrderId': 'The list identifier did not return.',
  'error.home.checkoutStartFailed': 'The table flow could not be started.',
  'error.home.paymentStatusFailed': 'Payment status could not be loaded.',
  'helper.home.toastAddedToList': 'Added to your food list',
  'helper.home.allergenTitle': 'Allergen warning',
  'helper.home.allergenConfirm': 'This meal contains these allergens:\n\n🔴 {allergens}\n\nDo you still want to add it to your list?',
  'cta.home.addAnyway': 'Add anyway',
  'headline.home.processingTitle': 'Your table is being prepared',
  'helper.home.processingCreateList': 'Preparing your list...',
  'helper.home.processingCapturePayment': 'Collecting payment...',
  'helper.home.processingSendSeller': 'Sending to seller...',
  'helper.home.processingDone': 'Done!',
  'headline.home.processingSuccess': 'Your table is ready!',
  'headline.home.tabHome': 'Home',
  'headline.home.tabMessages': 'Messages',
  'headline.home.tabOrders': 'Orders',
  'headline.home.tabNotifications': 'Notifications',
  'status.voice.addedAction': 'Added to your food list',
  'status.voice.orderSummaryAction': 'Your food list is ready',
};

const HOME_SUBTITLE_GENERIC_VARIANTS = [
  'Bugün ne yemek istersin?',
  'Canın ne çekiyorsa ona bakalım.',
  'Sana güzel bir şey öneririm.',
  'En çok satanlara bir göz atalım mı?',
  'Birlikte hızlıca bir şey seçelim mi?',
  'Bence bugün kendini güzel bir yemekle şımart.',
] as const;

const HOME_SUBTITLE_DAYPART_VARIANTS = {
  morning: [
    'Kahvaltıda ne istersin?',
    'Kahvaltını yaptın mı, acıktın mı?',
    'Sana mis gibi bir kahvaltı öneririm.',
    'Bugün hafif mi gidelim, doyurucu mu?',
  ],
  noon: [
    'Ne yemek istersin, beraber seçelim.',
    'Sana şimdi iyi gidecek bir şey öneririm.',
    'Öğlen acıktın mı, ne yiyelim?',
    'Bir tık ev yemeği moduna geçelim mi?',
  ],
  evening: [
    'Canın ne istiyorsa ona gidelim.',
    'Sana sıcacık bir şey öneririm.',
    'Akşam yemeği için ne düşünüyorsun?',
    'Bugün menüyü beraber toparlayalım mı?',
  ],
} as const;

function getPreferredLocale(): SupportedLocale {
  try {
    const locale = Intl.DateTimeFormat().resolvedOptions().locale?.toLowerCase?.() ?? 'tr';
    return locale.startsWith('en') ? 'en' : 'tr';
  } catch {
    return 'tr';
  }
}

export function t(key: BrandCopyKey): string {
  if (getPreferredLocale() === 'en') {
    return brandCopyEn[key] ?? brandCopy[key];
  }
  return brandCopy[key];
}

export function formatCopy(
  key: BrandCopyKey,
  values: Record<string, string | number>,
): string {
  return Object.entries(values).reduce(
    (message, [token, value]) => message.replace(new RegExp(`\\{${token}\\}`, 'g'), String(value)),
    t(key),
  );
}

export function randomHomeGreetingSubtitle(date = new Date()): string {
  const hour = date.getHours();
  const dayPart =
    hour < 11
      ? 'morning'
      : hour < 17
        ? 'noon'
        : 'evening';

  const pool = [
    ...HOME_SUBTITLE_DAYPART_VARIANTS[dayPart],
    ...HOME_SUBTITLE_GENERIC_VARIANTS,
  ];

  return pool[Math.floor(Math.random() * pool.length)] ?? 'Bugün ne yesek?';
}

export function stockLine(totalStock: number, remainingStock: number): string {
  return `${remainingStock} ${t('status.home.stockLineSuffix')} ${t('helper.home.stockLinePrefix')}`;
}

export function requestErrorLine(status: number): string {
  return `${t('error.home.requestFailed')} (${status})`;
}
