# Generated by Django 4.2.30 on 2026-06-10 19:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanceReconciliationReports',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_type', models.CharField(max_length=30)),
                ('actor_id', models.UUIDField()),
                ('report_type', models.CharField(max_length=50)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('file_url', models.URLField(blank=True, max_length=2048, null=True)),
                ('checksum', models.CharField(blank=True, max_length=255, null=True)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'finance_reconciliation_reports',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('provider_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('provider_reference_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.CharField(max_length=30)),
                ('callback_payload_json', models.JSONField(blank=True, null=True)),
                ('signature_valid', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.users')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orders')),
            ],
            options={
                'db_table': 'payment_attempts',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PaymentDisputeCases',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider_case_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('case_type', models.CharField(max_length=50)),
                ('reason_code', models.CharField(blank=True, max_length=100, null=True)),
                ('liability_party', models.CharField(max_length=30)),
                ('liability_ratio_json', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(max_length=30)),
                ('evidence_bundle_json', models.JSONField(blank=True, null=True)),
                ('opened_at', models.DateTimeField()),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orders')),
                ('payment_attempt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='payments.paymentattempts')),
            ],
            options={
                'db_table': 'payment_dispute_cases',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FinanceAdjustments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payments.paymentdisputecases')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.orders')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.users')),
            ],
            options={
                'db_table': 'finance_adjustments',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CommissionSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_rate', models.DecimalField(decimal_places=4, max_digits=5)),
                ('is_active', models.BooleanField()),
                ('effective_from', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.adminusers')),
            ],
            options={
                'db_table': 'commission_settings',
                'managed': True,
            },
        ),
    ]
